import type { Lesson, Unit } from './starter-lessons'

export const BUILDER_UNITS: Unit[] = [
  // ─────────────────────────────────────────────
  // UNIT 1 — Know Your Investments
  // ─────────────────────────────────────────────
  {
    id: 'b-unit-1',
    title: 'Know Your Investments',
    subtitle: 'Stocks, ETFs, index funds — and how to read them.',
    color: 'bg-brand-purple/20',
    borderColor: 'border-brand-purple',
    lessons: [
      {
        id: 'b1-l1',
        title: 'What You Already Know',
        emoji: '🔁',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '🔁',
            heading: 'What You Already Know',
            body: "Before we go deeper, let's make sure the foundation is solid.",
          },
          {
            type: 'text',
            emoji: '🧱',
            heading: 'The core ideas',
            body: "A stock is a piece of ownership in a company. The stock market is where those pieces are bought and sold. Prices move based on supply and demand — more buyers = price up, more sellers = price down.",
          },
          {
            type: 'text',
            emoji: '🛒',
            heading: 'You need a broker',
            body: "To buy or sell stock, you go through a broker — an app or platform like Fidelity, Robinhood, or Schwab. They execute your orders on the market.",
          },
          {
            type: 'fact',
            emoji: '📊',
            heading: 'The S&P 500 is your benchmark',
            body: "The S&P 500 tracks 500 of the largest US companies. It's the measuring stick investors use. If your investments are beating the S&P 500 return, you're doing well.",
          },
          {
            type: 'tap-reveal',
            emoji: '💡',
            heading: 'What makes the Builder track different?',
            body: 'Tap to find out.',
            tapReveal: "The Starter track gave you the vocabulary. The Builder track gives you the skills — how to read a stock page, how to research a company, how to place orders, and how to build an actual portfolio that can make you money.",
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "The S&P 500 goes up 12% this year. Your portfolio goes up 8%. How did you perform?",
              options: [
                'Great — 8% is still a profit',
                'Below the benchmark — the market outperformed you',
                'Exactly average',
                'You lost money',
              ],
              correctIndex: 1,
              explanation: "8% is a gain, but since the market returned 12%, you underperformed the benchmark. Experienced investors compare returns to the S&P 500 to know if their stock-picking is actually adding value.",
            },
          },
          {
            type: 'complete',
            emoji: '✅',
            heading: "Foundation confirmed.",
            body: "You're ready to go deeper. Let's talk about the different types of investments available to you.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b1-l2',
        title: 'Types of Investments',
        emoji: '🗂️',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '🗂️',
            heading: 'Types of Investments',
            body: "Stocks are just one option. Here's the full picture.",
          },
          {
            type: 'text',
            emoji: '🏢',
            heading: 'Individual stocks',
            body: "Buying shares of a single company — Apple, Nike, Tesla. High potential reward, but your risk is tied to that one company. If it struggles, you lose. If it soars, you win big.",
          },
          {
            type: 'text',
            emoji: '🧺',
            heading: 'ETFs — Exchange-Traded Funds',
            body: "A basket of many stocks bundled into one. Buy one share of an S&P 500 ETF (like VOO or SPY) and you instantly own a tiny piece of 500 companies. They trade on the market just like regular stocks.",
          },
          {
            type: 'text',
            emoji: '📦',
            heading: 'Index funds',
            body: "Very similar to ETFs, but usually only available through a brokerage (not traded on exchanges like regular stocks). They track an index like the S&P 500. Lower fees than most actively managed funds.",
          },
          {
            type: 'fact',
            emoji: '📈',
            heading: 'Why ETFs and index funds win long-term',
            body: "Studies show that over 10+ years, more than 90% of professional fund managers fail to beat a simple S&P 500 index fund. Buying the whole market consistently outperforms most stock pickers.",
          },
          {
            type: 'tap-reveal',
            emoji: '🤔',
            heading: 'What about mutual funds?',
            body: 'Tap to find out.',
            tapReveal: "Mutual funds pool money from many investors and are managed by professionals who pick stocks. The problem: they charge high fees (often 1–2% per year) and most still underperform simple index funds. ETFs and index funds are generally the better choice.",
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "You want instant exposure to 500 companies with one purchase and low fees. Which investment is best?",
              options: [
                'Buying shares of your 5 favorite companies',
                'A high-fee mutual fund',
                'An S&P 500 ETF like VOO or SPY',
                'A savings bond',
              ],
              correctIndex: 2,
              explanation: "An S&P 500 ETF gives you instant diversification, low fees, and tracks the overall market. It's the most efficient way to own a broad slice of the US economy.",
            },
          },
          {
            type: 'complete',
            emoji: '🗂️',
            heading: 'You know your options.',
            body: "Individual stocks, ETFs, index funds — each has its place. Most investors use a mix.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b1-l3',
        title: 'How to Read a Stock Page',
        emoji: '📊',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '📊',
            heading: 'How to Read a Stock Page',
            body: "Every broker shows you the same data. Here's what it all means.",
          },
          {
            type: 'text',
            emoji: '💲',
            heading: 'The price and change',
            body: "The current price is what one share costs right now. The change shows how much it moved today — in dollars and percent. A green +2.4% means the stock is up 2.4% from yesterday's closing price.",
          },
          {
            type: 'text',
            emoji: '📅',
            heading: '52-week high and low',
            body: "This shows the highest and lowest price the stock has traded in the past year. If a stock is near its 52-week low, it may be a discount. Near its 52-week high means it's been strong — but it might also be overpriced.",
          },
          {
            type: 'chart-demo',
            heading: 'Where is the price in its yearly range?',
            demoType: 'price-range',
          },
          {
            type: 'fact',
            emoji: '🔢',
            heading: 'Market cap — the company\'s total size',
            body: "Market cap = share price × total shares. Apple's market cap is around $3 trillion — that's what the market thinks the whole company is worth. It's how you compare company sizes.",
          },
          {
            type: 'text',
            emoji: '📏',
            heading: 'The P/E ratio',
            body: "P/E stands for Price-to-Earnings. It tells you how much investors are paying for every $1 the company earns. A P/E of 20 means investors pay $20 per $1 of profit. High P/E = high expectations. Low P/E = possibly undervalued — or struggling.",
          },
          {
            type: 'tap-reveal',
            emoji: '📉',
            heading: 'What is volume?',
            body: 'Tap to find out.',
            tapReveal: "Volume is the number of shares traded today. High volume means a lot of people are actively buying or selling — price moves on high volume are more significant than moves on low volume. A stock spiking 5% on huge volume is a much stronger signal than 5% on thin volume.",
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "A stock has a P/E ratio of 50. The average for its industry is 20. What does this suggest?",
              options: [
                'The stock is definitely a bargain',
                'The stock is priced for high growth — investors have high expectations',
                'The company is losing money',
                'The stock is about to crash',
              ],
              correctIndex: 1,
              explanation: "A high P/E relative to peers means investors expect strong future growth. It's not automatically bad — but if the company doesn't deliver, the price can drop hard. Always ask: is the P/E justified by the growth rate?",
            },
          },
          {
            type: 'complete',
            emoji: '📊',
            heading: "You can read a stock page.",
            body: "Price, change, 52-week range, market cap, P/E, volume — you know what they mean and why they matter.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b1-l4',
        title: 'Unit 1 Quiz',
        emoji: '🏆',
        xpReward: 30,
        slides: [
          {
            type: 'intro',
            emoji: '🏆',
            heading: 'Unit 1 Quiz',
            body: "Investments, ETFs, stock pages — let's lock it in.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 1 of 4',
            quiz: {
              question: "What is the main advantage of an ETF over buying individual stocks?",
              options: [
                'ETFs always go up',
                'ETFs give you instant diversification across many companies with one purchase',
                'ETFs have no risk',
                'ETFs are only for professional investors',
              ],
              correctIndex: 1,
              explanation: "One ETF can hold hundreds of stocks. This means a single bad company won't significantly hurt your investment.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 2 of 4',
            quiz: {
              question: "A stock's P/E ratio is 15, while its competitors average 30. What might this signal?",
              options: [
                'The stock is definitely a scam',
                'The stock may be undervalued — or the market expects slower growth',
                'The company is the best in its industry',
                'The stock will double in price tomorrow',
              ],
              correctIndex: 1,
              explanation: "A lower P/E than peers can mean the stock is undervalued — a potential opportunity. Or it means the market expects the company to grow more slowly. You need to dig into the business to know which it is.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 3 of 4',
            quiz: {
              question: "A stock jumps 8% today on very high volume. What does the high volume tell you?",
              options: [
                'Nothing — volume is irrelevant',
                "The move is likely significant — lots of real buying activity backed it",
                'The stock is being manipulated',
                'The company is releasing earnings',
              ],
              correctIndex: 1,
              explanation: "Volume confirms price moves. A big move with high volume signals real conviction from buyers or sellers. The same move on low volume could just be noise.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 4 of 4',
            quiz: {
              question: "Market cap is calculated as:",
              options: [
                'Share price ÷ total shares',
                'Share price × total shares outstanding',
                'Annual revenue × 10',
                'Total profit for the year',
              ],
              correctIndex: 1,
              explanation: "Market cap = share price × total shares. It's what the market thinks the entire company is worth right now.",
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Unit 1 Complete!',
            body: "You can identify investment types, read a stock page, and understand key metrics. That's more than most adults know.",
            xpReward: 30,
          },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // UNIT 2 — Reading the Market
  // ─────────────────────────────────────────────
  {
    id: 'b-unit-2',
    title: 'Reading the Market',
    subtitle: 'Bull markets, bear markets, and how to research stocks.',
    color: 'bg-brand-green/10',
    borderColor: 'border-brand-green',
    lessons: [
      {
        id: 'b2-l1',
        title: 'Bull vs. Bear Markets',
        emoji: '🐂🐻',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '🐂',
            heading: 'Bull vs. Bear Markets',
            body: "You'll hear these terms constantly. Here's exactly what they mean.",
          },
          {
            type: 'text',
            emoji: '🐂',
            heading: 'Bull market — the good times',
            body: "A bull market is when stock prices are rising and the overall market is trending upward for a sustained period. Officially, a bull market is when the market rises 20% or more from a recent low. The economy is usually growing, unemployment is low, and investor confidence is high.",
          },
          {
            type: 'text',
            emoji: '🐻',
            heading: 'Bear market — the hard times',
            body: "A bear market is when the market falls 20% or more from a recent high. They're scary — but they're normal. The US has had about 26 bear markets since 1928. The average bear market lasts about 9–10 months.",
          },
          {
            type: 'fact',
            emoji: '📈',
            heading: 'Bull markets last much longer',
            body: "The average bull market lasts nearly 3 years, and the average gain is about 114%. So for every painful bear market, there's a much longer, more profitable bull market waiting on the other side.",
          },
          {
            type: 'text',
            emoji: '🌊',
            heading: 'Corrections — smaller pullbacks',
            body: "A correction is a drop of 10–20%. These are even more common than bear markets — they happen almost every year and are completely normal. Most corrections reverse within a few months. New investors often panic during corrections unnecessarily.",
          },
          {
            type: 'chart-demo',
            heading: 'See what each phase looks like',
            demoType: 'bull-bear',
          },
          {
            type: 'tap-reveal',
            emoji: '💡',
            heading: 'How do you know which market we\'re in?',
            body: 'Tap to find out.',
            tapReveal: "Look at the S&P 500 trend. Up 20%+ from a low = bull market. Down 20%+ from a high = bear market. Down 10–20% = correction. Most financial news sites display this in real time. You don't need to guess — the data is public.",
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "The S&P 500 has dropped 25% from its all-time high over the last 8 months. What is this called?",
              options: [
                'A correction',
                'A bull market',
                'A bear market',
                'A recession',
              ],
              correctIndex: 2,
              explanation: "A drop of 20%+ from a recent high is officially a bear market. A recession is an economic term (two consecutive quarters of GDP decline) — related but different from a bear market.",
            },
          },
          {
            type: 'complete',
            emoji: '🐂',
            heading: 'You speak the language.',
            body: "Bull markets, bear markets, corrections — you know the difference and what each one means for your strategy.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b2-l2',
        title: 'How to Research a Company',
        emoji: '🔍',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '🔍',
            heading: 'How to Research a Company',
            body: "Don't buy a stock because someone hyped it. Buy it because you understand the business.",
          },
          {
            type: 'text',
            emoji: '❓',
            heading: 'Start with the business model',
            body: "Can you explain in one sentence how this company makes money? If you can't, don't invest. Amazon: sells products and cloud computing services. Nike: sells athletic apparel and footwear. Clarity first, investment second.",
          },
          {
            type: 'text',
            emoji: '💰',
            heading: 'Check the financials',
            body: "Look at revenue trend (is it growing year over year?), profit margins (does it actually make money?), and debt levels (is it drowning in loans?). All publicly traded companies file this data with the SEC — it's public, free, and required by law.",
          },
          {
            type: 'fact',
            emoji: '📋',
            heading: 'The earnings report is your best friend',
            body: "Four times a year, every public company reports its financials — revenue, profit, growth. This is called an earnings report. Compare it to what analysts expected. Beat expectations → stock usually rises. Miss expectations → stock usually drops.",
          },
          {
            type: 'text',
            emoji: '🏆',
            heading: 'The competitive moat',
            body: "A 'moat' is a durable competitive advantage that protects a company from competition. Apple's moat = ecosystem and brand loyalty. Google's moat = search dominance. The wider the moat, the safer the investment. Ask: why can't a competitor take this company's customers?",
          },
          {
            type: 'tap-reveal',
            emoji: '🔗',
            heading: 'Where do you find this information?',
            body: 'Tap to find out.',
            tapReveal: "Free resources: Yahoo Finance, Google Finance, and SEC.gov (for official filings). Search 'AAPL earnings' or 'Nike annual report' and you'll find everything. Paid tools like Bloomberg or Morningstar go deeper — but Yahoo Finance is enough to start.",
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "A company reports revenue grew 40% year over year and profit margins expanded. What does this likely mean for the stock?",
              options: [
                'The stock will definitely drop because growth is unsustainable',
                'Strong growth and improving profitability are positive signals — stock likely rises',
                'Nothing — revenue doesn\'t affect stock price',
                'The company is about to go bankrupt',
              ],
              correctIndex: 1,
              explanation: "Revenue growth + expanding margins = the company is growing AND becoming more efficient. These are exactly the signals investors look for. The market tends to reward this combination.",
            },
          },
          {
            type: 'complete',
            emoji: '🔍',
            heading: 'Research like a pro.',
            body: "Business model, financials, earnings, competitive moat — four questions that separate informed investors from gamblers.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b2-l3',
        title: 'Diversification Deep Dive',
        emoji: '🌐',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '🌐',
            heading: 'Diversification Deep Dive',
            body: "You know what diversification is. Now let's get tactical about it.",
          },
          {
            type: 'text',
            emoji: '🏭',
            heading: 'Diversify across sectors',
            body: "The market is divided into sectors: Technology, Healthcare, Consumer Goods, Energy, Finance, and more. If all your stocks are in tech, a tech downturn wipes your whole portfolio. Owning stocks across multiple sectors cushions the blow.",
          },
          {
            type: 'text',
            emoji: '🌍',
            heading: 'Diversify across geographies',
            body: "US companies only? A US recession hits you hard. Adding international exposure — European, Asian, or emerging market funds — means no single country's problems can destroy your portfolio.",
          },
          {
            type: 'fact',
            emoji: '📊',
            heading: 'Correlation is what you\'re fighting',
            body: "Stocks that move together don't help each other. If Apple and Microsoft both drop when tech is down, owning both doesn't protect you. True diversification means owning assets that don't all move the same direction at the same time.",
          },
          {
            type: 'text',
            emoji: '📐',
            heading: 'How many stocks do you actually need?',
            body: "Research shows that most of the benefit of diversification comes from the first 15–20 stocks. After about 20–25 stocks across different sectors, additional stocks add very little extra protection. Quality beats quantity.",
          },
          {
            type: 'tap-reveal',
            emoji: '🤔',
            heading: 'What about bonds?',
            body: 'Tap to find out.',
            tapReveal: "Bonds are loans you give to governments or companies in exchange for regular interest payments. They're less risky than stocks but grow more slowly. Many investors mix stocks and bonds — younger investors lean stock-heavy (more time to recover from drops), older investors lean bond-heavy (need stability).",
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "You own 10 tech stocks. The tech sector crashes 30%. What mistake did you make?",
              options: [
                'You had too many stocks',
                'You failed to diversify across sectors — all your eggs were in tech',
                'You should have owned fewer stocks',
                'You bought at the wrong time',
              ],
              correctIndex: 1,
              explanation: "10 stocks sounds diversified, but 10 tech stocks move together. Real diversification spreads across sectors so one industry's bad day doesn't wreck your whole portfolio.",
            },
          },
          {
            type: 'complete',
            emoji: '🌐',
            heading: 'Diversification is a strategy, not an accident.',
            body: "Sector spread, geographic spread, correlation awareness — you now know how to build a portfolio that's actually protected.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b2-l4',
        title: 'Unit 2 Quiz',
        emoji: '🏆',
        xpReward: 30,
        slides: [
          {
            type: 'intro',
            emoji: '🏆',
            heading: 'Unit 2 Quiz',
            body: "Markets, research, diversification — let's see what stuck.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 1 of 4',
            quiz: {
              question: "The market drops 12% over 2 months. This is best described as:",
              options: [
                'A bear market',
                'A recession',
                'A correction',
                'A crash',
              ],
              correctIndex: 2,
              explanation: "A drop of 10–20% is a correction — normal and common. Bear markets are 20%+ drops. Corrections feel scary but typically reverse within months.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 2 of 4',
            quiz: {
              question: "Before buying a stock, the most important first question is:",
              options: [
                "What did Reddit say about it?",
                "How can I explain in one sentence how this company makes money?",
                "Is the stock price under $10?",
                "Did a celebrity invest in it?",
              ],
              correctIndex: 1,
              explanation: "If you can't explain the business model in one sentence, you don't understand what you're buying. Understanding the business is the foundation of every investment decision.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 3 of 4',
            quiz: {
              question: "You own 20 stocks: 10 tech, 5 healthcare, 3 energy, 2 finance. A tech crash wipes out your tech stocks. How is your overall portfolio affected?",
              options: [
                'The whole portfolio drops 100%',
                'About 50% of your portfolio is affected — your non-tech holdings provide a buffer',
                'Nothing happens — 20 stocks means you\'re fully protected',
                'Only the 3 energy stocks are affected',
              ],
              correctIndex: 1,
              explanation: "Tech = 10 of 20 stocks = roughly 50% of a portfolio if equally weighted. The other sectors provide protection. This is exactly why sector diversification matters.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 4 of 4',
            quiz: {
              question: "A company's earnings report beats analyst expectations by 20%. What typically happens?",
              options: [
                'The stock drops because expectations were already priced in',
                'Nothing — earnings reports don\'t move stocks',
                'The stock likely rises as investors reward the outperformance',
                'The company gets delisted',
              ],
              correctIndex: 2,
              explanation: "Beating estimates is a strong positive signal. Markets are forward-looking — a big earnings beat tells investors the company is doing better than expected, and demand for the stock increases.",
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Unit 2 Complete!',
            body: "You can identify market conditions, research a company like a professional, and build a truly diversified portfolio.",
            xpReward: 30,
          },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // UNIT 3 — Making Your Move
  // ─────────────────────────────────────────────
  {
    id: 'b-unit-3',
    title: 'Making Your Move',
    subtitle: 'Orders, your first trade, and building a real portfolio.',
    color: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500',
    lessons: [
      {
        id: 'b3-l1',
        title: 'Risk vs. Reward',
        emoji: '⚖️',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '⚖️',
            heading: 'Risk vs. Reward',
            body: "Every investment is a tradeoff. Understanding it is your edge.",
          },
          {
            type: 'text',
            emoji: '📐',
            heading: 'The risk/reward ratio',
            body: "Before any trade, professionals ask: how much can I lose vs. how much can I gain? A risk/reward ratio of 1:3 means you're risking $1 to potentially make $3. You only need to be right 25% of the time to break even with that ratio.",
          },
          {
            type: 'text',
            emoji: '🎯',
            heading: 'Your entry point matters',
            body: "Where you buy changes your risk. Buying a stock at its 52-week low carries different risk than buying it at an all-time high. Both can work — but the risk profile is completely different. Always know what you're risking before you buy.",
          },
          {
            type: 'fact',
            emoji: '🛑',
            heading: 'Define your exit before you enter',
            body: "Professional traders always decide two things before buying: (1) the price at which they'll sell to take profits, and (2) the price at which they'll cut losses. This is called having a plan. Most beginners skip this step — and regret it.",
          },
          {
            type: 'text',
            emoji: '🧠',
            heading: 'Volatility = risk made visible',
            body: "Volatile stocks swing wildly in price. Low-volatility stocks move slowly. High volatility = higher potential reward but also higher potential loss. Match your risk tolerance to your investment. Beginners should start with lower-volatility assets.",
          },
          {
            type: 'tap-reveal',
            emoji: '💡',
            heading: 'What is beta?',
            body: 'Tap to find out.',
            tapReveal: "Beta measures a stock's volatility compared to the overall market. Beta of 1 = moves with the market. Beta of 2 = moves twice as much as the market (up or down). Beta of 0.5 = half as volatile. You can find a stock's beta on any financial site.",
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "You're considering a trade where you could lose $100 or gain $150. What is your risk/reward ratio?",
              options: ['1:1', '1:1.5', '2:1', '3:1'],
              correctIndex: 1,
              explanation: "Risk $100, reward $150 = 1:1.5. You need to be right more than 40% of the time to profit with this ratio. A 1:2 or 1:3 ratio is generally preferred — you can be wrong more often and still come out ahead.",
            },
          },
          {
            type: 'complete',
            emoji: '⚖️',
            heading: 'Risk/reward is your compass.',
            body: "Every trade has a tradeoff. Now you know how to evaluate it before you pull the trigger.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b3-l2',
        title: 'Limit Orders vs. Market Orders',
        emoji: '🛒',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '🛒',
            heading: 'Limit Orders vs. Market Orders',
            body: "There's more than one way to buy a stock. The difference matters.",
          },
          {
            type: 'text',
            emoji: '⚡',
            heading: 'Market order — buy now, at any price',
            body: "A market order tells your broker: buy this stock immediately at whatever the current price is. It's fast and guaranteed to fill — but in a fast-moving market, the price you pay might be slightly higher than what you saw on the screen.",
          },
          {
            type: 'text',
            emoji: '🎯',
            heading: 'Limit order — buy only at my price',
            body: "A limit order says: I'll only buy if the price reaches a specific level I set. Set a limit of $50 on a $52 stock, and you wait. If it drops to $50, you buy automatically. If it never reaches $50, you don't buy.",
          },
          {
            type: 'fact',
            emoji: '📋',
            heading: 'When to use each',
            body: "Market orders: when you're confident in the stock and want in NOW regardless of a small price difference. Limit orders: when you're disciplined about your entry price, or when the stock is very volatile and you don't want to overpay.",
          },
          {
            type: 'text',
            emoji: '🛑',
            heading: 'Stop-loss orders — your safety net',
            body: "A stop-loss tells your broker: if this stock drops to $X, sell it automatically. It caps your downside. Example: you buy at $100, set a stop-loss at $90. If it drops to $90, it sells — you lose $10, not $40. Every serious investor uses stop-losses.",
          },
          {
            type: 'tap-reveal',
            emoji: '🤔',
            heading: 'What is a stop-limit order?',
            body: 'Tap to find out.',
            tapReveal: "A stop-limit combines both. You set a trigger price (stop) and a minimum sell price (limit). Example: stop at $90, limit at $88. When price hits $90, a limit order to sell at $88 or better activates. The risk: if the stock gaps through $88, you might not sell at all. In a crash, a plain stop-loss is safer.",
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "You want to buy a stock only if it drops from $75 to $70. Which order type do you use?",
              options: [
                'Market order at $75',
                'Limit order set at $70',
                'Stop-loss order at $70',
                'Call your broker directly',
              ],
              correctIndex: 1,
              explanation: "A limit order lets you set the exact price you're willing to pay. The order sits waiting — and executes automatically if the stock reaches your price.",
            },
          },
          {
            type: 'complete',
            emoji: '🛒',
            heading: 'You control your entry.',
            body: "Market orders for speed. Limit orders for precision. Stop-losses for protection. These are professional tools — now they're yours.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b3-l3',
        title: 'Your First Trade',
        emoji: '🚦',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '🚦',
            heading: 'Your First Trade',
            body: "Step by step. Calm and confident.",
          },
          {
            type: 'text',
            emoji: '1️⃣',
            heading: 'Step 1 — Do your homework first',
            body: "Before touching the app: understand the business, check the financials, know why you're buying this stock at this price. Write it down. If you can't articulate your reason, you're not ready.",
          },
          {
            type: 'text',
            emoji: '2️⃣',
            heading: 'Step 2 — Decide your position size',
            body: "How much are you going to invest? Apply the 1–2% rule. On a $1,000 portfolio, that's $10–$20 max at risk per trade. Start small. You can always add more as you gain confidence.",
          },
          {
            type: 'text',
            emoji: '3️⃣',
            heading: 'Step 3 — Set your exit levels before you enter',
            body: "Decide NOW: at what price will you take profits? At what price will you cut losses? Set a stop-loss order immediately after your purchase fills. Your future panicked self will thank you.",
          },
          {
            type: 'text',
            emoji: '4️⃣',
            heading: 'Step 4 — Place the order',
            body: "Search the ticker. Choose shares or dollar amount. Select order type (limit or market). Review the details. Confirm. That's it. The trade takes seconds once you're ready.",
          },
          {
            type: 'fact',
            emoji: '🧘',
            heading: "What to do after you buy",
            body: "Step away. Watching every tick of a stock you just bought causes bad decisions. Check it once a day, not once an hour. Professional investors review weekly. The people who win long-term are the ones who stay calm.",
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "You just bought a stock at $50. You set a stop-loss at $45. The stock drops to $45. What happens?",
              options: [
                'Nothing — you have to manually sell',
                'Your broker automatically sells your shares near $45, limiting your loss',
                'Your broker buys more shares at $45',
                'Your account gets frozen',
              ],
              correctIndex: 1,
              explanation: "A stop-loss executes automatically when the price hits your trigger. You lock in a known loss instead of watching it spiral further. It's not a failure — it's a plan working exactly as designed.",
            },
          },
          {
            type: 'complete',
            emoji: '🚦',
            heading: "You're ready to trade.",
            body: "Research, sizing, exit plan, order placement — the four steps of every professional trade. Now they're your four steps.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b3-l4',
        title: 'Building a Beginner Portfolio',
        emoji: '🏗️',
        xpReward: 10,
        slides: [
          {
            type: 'intro',
            emoji: '🏗️',
            heading: 'Building a Beginner Portfolio',
            body: "What does an actual smart beginner portfolio look like? Let's build one.",
          },
          {
            type: 'text',
            emoji: '🧱',
            heading: 'The core — your foundation',
            body: "Start with 50–70% of your portfolio in a broad market ETF like VOO (S&P 500) or VTI (total US market). This is your stable base. It grows with the economy, it diversifies automatically, and it requires almost no monitoring.",
          },
          {
            type: 'text',
            emoji: '🔨',
            heading: 'The growth layer',
            body: "Allocate 20–30% to individual stocks or sector ETFs you've researched and believe in. Pick companies whose business model you understand, in sectors you follow. Keep it to 5–10 positions. This is where your research pays off.",
          },
          {
            type: 'text',
            emoji: '💵',
            heading: 'Keep cash on hand',
            body: "Keep 5–10% in cash (or a money market fund). This isn't dead money — it's opportunity money. When a stock you've been watching drops 20%, cash lets you buy the dip. Investors who are always fully invested can never take advantage of sales.",
          },
          {
            type: 'fact',
            emoji: '🔄',
            heading: 'Rebalancing — stay on track',
            body: "Over time, your portfolio will drift as some stocks grow faster than others. Rebalancing means selling a little of what's grown too big and adding to what's lagged — to stay near your target allocation. Most investors rebalance once or twice a year.",
          },
          {
            type: 'tap-reveal',
            emoji: '🎯',
            heading: 'Sample beginner portfolio',
            body: 'Tap to see an example.',
            tapReveal: "Example $1,000 portfolio: $600 in VOO (S&P 500 ETF), $150 in a tech ETF like QQQ, $150 spread across 2–3 individual stocks you've researched, $100 in cash. Simple, diversified, low-maintenance — and you understand every piece of it.",
          },
          {
            type: 'chart-demo',
            heading: 'Watch what diversification does to your risk',
            demoType: 'portfolio-bars',
          },
          {
            type: 'quiz',
            emoji: '🧠',
            heading: 'Quick check!',
            quiz: {
              question: "Why should a beginner keep 5–10% of their portfolio in cash?",
              options: [
                'Cash earns the best interest rates',
                'It creates opportunities to buy during market dips without selling other positions',
                'Brokers require it',
                'Cash is safer than any investment',
              ],
              correctIndex: 1,
              explanation: "Cash = flexibility. When markets drop and stocks go on sale, investors with cash can buy more. Those who are 100% invested can only watch. Opportunity capital is a real edge.",
            },
          },
          {
            type: 'complete',
            emoji: '🏗️',
            heading: "Your blueprint is ready.",
            body: "Core ETF foundation + growth layer + opportunity cash. Rebalance annually. This is a real, professional-grade approach to building wealth.",
            xpReward: 10,
          },
        ],
      },
      {
        id: 'b3-l5',
        title: 'Builder Track Final Quiz',
        emoji: '🎓',
        xpReward: 50,
        slides: [
          {
            type: 'intro',
            emoji: '🎓',
            heading: 'Builder Track Final Quiz',
            body: "Everything you've built — let's put it to the test.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 1 of 5',
            quiz: {
              question: "A stock has a beta of 2.5. The market drops 10%. Approximately how much does this stock drop?",
              options: ['2.5%', '10%', '25%', '100%'],
              correctIndex: 2,
              explanation: "Beta of 2.5 means the stock moves 2.5× the market. If the market drops 10%, this stock would drop approximately 25%. High beta = high volatility in both directions.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 2 of 5',
            quiz: {
              question: "You set a limit order to buy a stock at $40. The stock is currently trading at $45. What happens?",
              options: [
                'You buy immediately at $45',
                'Your order sits waiting — it only fills if the stock drops to $40',
                'Your order is rejected',
                'You buy at $42.50 — the midpoint',
              ],
              correctIndex: 1,
              explanation: "A limit order will only execute at your specified price or better. It waits patiently. If the stock never reaches $40, your order never fills.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 3 of 5',
            quiz: {
              question: "Before placing a trade, which step do professional traders take FIRST?",
              options: [
                'Check social media for tips',
                'Define how much they can lose and at what price they will exit',
                'Call their broker',
                'Wait for the stock to reach an all-time high',
              ],
              correctIndex: 1,
              explanation: "Planning your exit before your entry is fundamental. Knowing your stop-loss and profit target before you buy removes emotion from the equation.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 4 of 5',
            quiz: {
              question: "Your portfolio is 100% tech stocks. The tech sector drops 35%. What would have protected you?",
              options: [
                'Buying more tech stocks',
                'Using market orders instead of limit orders',
                'Diversifying across sectors and asset classes',
                'Keeping all cash in a savings account',
              ],
              correctIndex: 2,
              explanation: "Sector diversification is the protection. If you had spread across tech, healthcare, consumer goods, and international funds, a tech crash would only hurt part of your portfolio.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Question 5 of 5',
            quiz: {
              question: "For a beginner with $500, which portfolio structure makes the most sense?",
              options: [
                '$500 into one stock you heard about on social media',
                '$350 in an S&P 500 ETF, $100 in 2-3 researched stocks, $50 cash',
                '$500 in options contracts',
                '$500 in the single highest-beta stock available',
              ],
              correctIndex: 1,
              explanation: "A core ETF base, a small individual stock layer, and cash on hand is the textbook beginner approach. Diversified, understandable, and positioned to grow while protecting against catastrophic loss.",
            },
          },
          {
            type: 'complete',
            emoji: '🏆',
            heading: 'Builder Track Complete!',
            body: "You can read a stock page, research a company, understand market cycles, place orders like a pro, and build a real portfolio. You are ready for the Leveler track.",
            xpReward: 50,
          },
        ],
      },
    ],
  },
] as Unit[]
