import type { Lesson, Unit } from '@/lib/starter-lessons'

export const LEVELER_UNITS: Unit[] = [
  {
    id: 'lv1',
    title: 'Reading the Charts',
    subtitle: 'Candlesticks, support, resistance, and volume.',
    color: 'bg-brand-purple/20',
    borderColor: 'border-brand-purple',
    lessons: [
      {
        id: 'lv1-l1',
        title: 'How to Read a Price Chart',
        emoji: '📊',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '📊',
            heading: 'Charts Are Your Roadmap',
            body: "A price chart shows you where a stock has been — and gives you clues about where it might go. Once you know how to read one, you're thinking like a trader.",
          },
          {
            type: 'text',
            emoji: '🕯️',
            heading: 'Meet the Candlestick',
            body: 'The most common chart uses candlesticks. Each candle represents one time period — a day, hour, or week. A green candle means the price went up. A red candle means it went down.',
          },
          {
            type: 'chart-demo',
            demoType: 'candlestick-anatomy',
            emoji: '📐',
            heading: 'Four Numbers in Every Candle',
          },
          {
            type: 'text',
            emoji: '↔️',
            heading: 'The Two Axes',
            body: 'The X-axis (bottom) shows time. The Y-axis (right side) shows price. Reading left to right shows you the full history of what happened to the stock.',
          },
          {
            type: 'chart-demo',
            demoType: 'bull-bear',
            emoji: '📈',
            heading: 'Market Phases on a Chart',
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Quick Check',
            quiz: {
              question: 'What does a green candlestick tell you?',
              options: [
                'The stock closed higher than it opened',
                'The stock closed lower than it opened',
                "The stock didn't move",
                'The stock was halted',
              ],
              correctIndex: 0,
              explanation: 'Green means the closing price was higher than the opening price — the stock gained value during that time period.',
            },
          },
          {
            type: 'complete',
            emoji: '🎯',
            heading: 'Chart Reader Unlocked',
            body: "You now know how to decode a candlestick chart. Every trader started exactly where you are.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv1-l2',
        title: 'Support and Resistance',
        emoji: '🧲',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🧲',
            heading: 'Price Has Memory',
            body: "Stocks don't just bounce around randomly. They tend to stop and reverse at the same price levels over and over. This is support and resistance — the foundation of technical analysis.",
          },
          {
            type: 'text',
            emoji: '🛡️',
            heading: 'What Is Support?',
            body: "Support is a price floor — a level where buyers have consistently stepped in and pushed the price back up. Think of it as a trampoline. The stock falls to this level and bounces.",
          },
          {
            type: 'text',
            emoji: '🚧',
            heading: 'What Is Resistance?',
            body: 'Resistance is a price ceiling — a level where sellers have consistently pushed the price back down. The stock rises to this level and stalls. You learned this as the "ceiling" in the glossary.',
          },
          {
            type: 'fact',
            emoji: '🔄',
            heading: 'Old Resistance Becomes New Support',
            body: 'When a stock breaks through resistance (a "breakout"), that old ceiling often becomes the new floor. This flip is one of the most powerful patterns in technical analysis.',
          },
          {
            type: 'tap-reveal',
            emoji: '💡',
            heading: 'Why Do These Levels Exist?',
            body: 'Tap to understand the psychology behind support and resistance.',
            tapReveal: 'At support, buyers who missed a previous low are waiting. At resistance, holders who bought high are waiting to break even and sell. These collective decisions create predictable, repeating price behavior.',
          },
          {
            type: 'chart-demo',
            demoType: 'price-range',
            emoji: '📍',
            heading: 'See It In Action',
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Test Your Knowledge',
            quiz: {
              question: 'A stock keeps bouncing back up every time it hits $45. What is $45 called?',
              options: [
                'Resistance',
                'Support',
                'A breakout level',
                'A stop loss',
              ],
              correctIndex: 1,
              explanation: "A price level where the stock repeatedly bounces upward is called support — it's acting as a floor that buyers keep defending.",
            },
          },
          {
            type: 'complete',
            emoji: '🏆',
            heading: 'Support & Resistance Mastered',
            body: 'You can now identify the key levels that every serious trader watches.',
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv1-l3',
        title: 'What Volume Is Telling You',
        emoji: '📢',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '📢',
            heading: 'Volume Is the Truth Detector',
            body: 'Price tells you what happened. Volume tells you how serious it was. Learning to read volume separates traders who guess from traders who confirm.',
          },
          {
            type: 'text',
            emoji: '👥',
            heading: 'What Is Volume?',
            body: 'Volume is simply the number of shares traded during a time period. High volume means a lot of people are buying and selling. Low volume means the market is quiet.',
          },
          {
            type: 'fact',
            emoji: '✅',
            heading: 'Strong Move = Price + Volume',
            body: 'Price going up on high volume = lots of buyers, strong conviction. Price going up on low volume = only a few people interested — the move might not last.',
          },
          {
            type: 'text',
            emoji: '⚠️',
            heading: 'The Warning Sign',
            body: 'When a stock makes a big price move but volume is unusually low, be cautious. It could be a "fake out" — a small number of traders moving the price without real demand behind it.',
          },
          {
            type: 'tap-reveal',
            emoji: '🔍',
            heading: 'Volume at Support & Resistance',
            body: 'Tap to see why volume matters most at key price levels.',
            tapReveal: 'A breakout above resistance on heavy volume is a strong signal — it means many traders believe in the move. A breakout on light volume? Healthy skepticism. Wait for confirmation before committing.',
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Volume Check',
            quiz: {
              question: 'A stock breaks through resistance. Which scenario is the stronger signal?',
              options: [
                'Breakout on low volume',
                'Breakout on high volume',
                'Both are equally strong',
                "Volume doesn't matter for breakouts",
              ],
              correctIndex: 1,
              explanation: "High volume on a breakout means many traders are committed to the move — it's much more likely to hold than a low-volume breakout, which can easily reverse.",
            },
          },
          {
            type: 'complete',
            emoji: '🔊',
            heading: 'Volume Decoded',
            body: "You've added volume analysis to your toolkit. Now you can see what most people miss.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv1-l4',
        title: 'Charts Unit Quiz',
        emoji: '📝',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '📝',
            heading: 'Unit 1 Quiz',
            body: "Let's make sure the chart basics are locked in before moving forward.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: 'What do the "wicks" on a candlestick show?',
              options: [
                'The open and close prices',
                'The high and low prices during the period',
                'The volume traded',
                "The stock's moving average",
              ],
              correctIndex: 1,
              explanation: "The wicks (thin lines above and below the body) show the highest and lowest prices reached during the time period — even if the stock didn't close there.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: 'What typically happens when a stock breaks above an old resistance level?',
              options: [
                "Nothing — it usually falls right back",
                'The old resistance often becomes new support',
                'The stock immediately doubles',
                'Volume always drops',
              ],
              correctIndex: 1,
              explanation: 'When resistance is broken, that level often "flips" to support. Traders who missed the breakout now see it as a buying opportunity when price returns to that level.',
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: 'A stock drops sharply in price but on very low volume. What does this suggest?',
              options: [
                'A strong, confirmed downtrend',
                'The move may lack conviction and could reverse',
                'Guaranteed further losses',
                'Time to sell immediately',
              ],
              correctIndex: 1,
              explanation: 'Low volume on a price move means fewer participants are behind it. It could be a temporary dip rather than a real breakdown — always wait for confirmation.',
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Unit 1 Complete!',
            body: "Charts, support/resistance, and volume — you've got the technical analysis foundation.",
            xpReward: 20,
          },
        ],
      },
    ],
  },
  {
    id: 'lv2',
    title: 'Timing & Risk',
    subtitle: 'Position sizing, stop losses, and spotting manipulation.',
    color: 'bg-brand-green/10',
    borderColor: 'border-brand-green',
    lessons: [
      {
        id: 'lv2-l1',
        title: 'Short Term vs Long Term',
        emoji: '⏱️',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '⏱️',
            heading: 'Which Game Are You Playing?',
            body: "Some people hold stocks for years. Others for minutes. There's no universally right approach — but knowing which style fits your life is one of the most important decisions you'll make.",
          },
          {
            type: 'text',
            emoji: '🌱',
            heading: 'Long-Term Investing',
            body: "Buying and holding for months or years. You focus on the company's fundamentals — is the business actually growing? This is lower stress, lower maintenance, and historically very effective.",
          },
          {
            type: 'text',
            emoji: '⚡',
            heading: 'Short-Term Trading',
            body: 'Buying and selling within days, hours, or even minutes. You focus on charts and momentum. This requires more time, more skill, and significantly more emotional discipline.',
          },
          {
            type: 'fact',
            emoji: '📊',
            heading: 'The Numbers Are Honest',
            body: 'Studies show 70–80% of short-term traders lose money, especially in their first year. Long-term index investors have historically averaged 7–10% annual returns. Both can work — they require very different commitments.',
          },
          {
            type: 'tap-reveal',
            emoji: '💬',
            heading: 'Which One Is Right for You?',
            body: 'Tap to think through this honestly.',
            tapReveal: "Ask yourself: Do I have 1+ hours a day to watch markets? Can I stay calm when I lose $300 in an hour? If yes, short-term trading might suit you. If you want results without daily monitoring, long-term investing is likely the smarter play for your life right now.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Your Trading Style',
            quiz: {
              question: "Which approach focuses on a company's revenue, growth, and overall business quality?",
              options: [
                'Short-term trading',
                'Day trading',
                'Long-term investing',
                'Scalping',
              ],
              correctIndex: 2,
              explanation: "Long-term investors care about the underlying business. They hold through short-term noise because they believe in where the company is going over years — not days.",
            },
          },
          {
            type: 'complete',
            emoji: '🎯',
            heading: 'Style Decided',
            body: 'Understanding your investing style is the first step toward a real strategy.',
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv2-l2',
        title: 'Risk Management & Position Sizing',
        emoji: '🛡️',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🛡️',
            heading: 'Protecting What You Have',
            body: "Making money is important. But keeping it is everything. Risk management isn't about being cautious — it's about staying in the game long enough to win.",
          },
          {
            type: 'text',
            emoji: '1️⃣',
            heading: 'The 1% Rule',
            body: "Professional traders risk no more than 1–2% of their total account on any single trade. If you have $1,000, that means you're willing to lose a maximum of $10–$20 on one trade. Not the whole $1,000.",
          },
          {
            type: 'fact',
            emoji: '🧮',
            heading: 'Position Sizing in Practice',
            body: "If a stock is at $50 and you'd exit at $48 (a $2 loss per share), and your max risk is $20, you buy 10 shares ($20 ÷ $2 = 10). The math decides the quantity — not gut feeling.",
          },
          {
            type: 'text',
            emoji: '📉',
            heading: 'Why This Matters',
            body: "If you risk 50% of your account on one trade and lose, you need a 100% gain just to break even. If you risk 2% and lose, you need a 2.04% gain to recover. Small, controlled losses are survivable. Large ones aren't.",
          },
          {
            type: 'tap-reveal',
            emoji: '🔢',
            heading: 'The Math That Keeps You Safe',
            body: 'Tap to walk through a real position sizing example.',
            tapReveal: "Account: $5,000. Max risk per trade: 1% = $50. You want to buy a stock at $100 with a stop loss at $95 (risk = $5/share). Position size: $50 ÷ $5 = 10 shares. You're in the trade — with your risk defined before you buy.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Risk Management Check',
            quiz: {
              question: 'You have a $2,000 account. Using the 1% rule, what is the maximum you should risk on one trade?',
              options: ['$200', '$100', '$20', '$500'],
              correctIndex: 2,
              explanation: '1% of $2,000 = $20. This might feel small, but it means even 10 losses in a row only costs you $200 — leaving you $1,800 to recover, learn, and improve.',
            },
          },
          {
            type: 'complete',
            emoji: '🛡️',
            heading: 'Risk Managed',
            body: 'You now think about risk the way professionals do. This single habit separates lasting traders from those who blow up their accounts.',
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv2-l3',
        title: 'Stop Loss and Take Profit',
        emoji: '🎯',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🎯',
            heading: 'Know Your Exit Before You Enter',
            body: 'Amateurs decide when to sell based on how they feel. Professionals decide before they buy. Stop losses and take profits remove emotion from the most important decision in trading.',
          },
          {
            type: 'text',
            emoji: '🛑',
            heading: 'What Is a Stop Loss?',
            body: "A stop loss is a price you set below your entry. If the stock falls to that price, it automatically sells — cutting your loss before it gets worse. It's your safety net.",
          },
          {
            type: 'text',
            emoji: '💰',
            heading: 'What Is a Take Profit?',
            body: 'A take profit is a price target above your entry. When the stock hits that price, it automatically sells — locking in your gain before the market can take it back.',
          },
          {
            type: 'fact',
            emoji: '⚖️',
            heading: 'The Risk/Reward Ratio',
            body: "Good traders aim for a 2:1 or 3:1 reward-to-risk ratio. If you risk $10, your target should be $20–$30 profit. This means you can be wrong more than half the time and still make money overall.",
          },
          {
            type: 'tap-reveal',
            emoji: '💡',
            heading: 'Where to Put Your Stop Loss',
            body: 'Tap for a practical rule of thumb.',
            tapReveal: "Place your stop loss just below the most recent support level. If support breaks, you're out before major damage. If the stock respects support and keeps climbing, you stay in and let the profit run.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Stop & Target Math',
            quiz: {
              question: 'You buy at $50. Stop loss is $47 (risk: $3). For a 2:1 risk/reward ratio, where should your take profit be?',
              options: ['$53', '$56', '$60', '$47'],
              correctIndex: 1,
              explanation: '2:1 means profit target = 2× your risk. Risk is $3 (from $50 to $47), so target is $50 + $6 = $56.',
            },
          },
          {
            type: 'complete',
            emoji: '✅',
            heading: 'Exits Defined',
            body: "You now enter every trade with a plan. That alone puts you ahead of most beginners.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv2-l4',
        title: 'How to Spot Manipulation',
        emoji: '🔍',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🔍',
            heading: "Not Every Move Is Real",
            body: "Some price movements are driven by real business results. Others are manufactured by people trying to take your money. Knowing the difference keeps you safe.",
          },
          {
            type: 'text',
            emoji: '🐋',
            heading: 'Pump and Dump',
            body: 'A group buys a low-volume stock in bulk, then hypes it online. Retail investors pile in, pushing the price up. Then the group sells everything at the top — the price crashes, and latecomers hold the loss.',
          },
          {
            type: 'fact',
            emoji: '⚠️',
            heading: 'Warning Signs to Watch For',
            body: 'Sudden 20–50%+ price spike with no news. Heavy promotion from unknown social media accounts. Tiny company, little or no revenue. Celebrities or influencers pushing the stock.',
          },
          {
            type: 'text',
            emoji: '📊',
            heading: 'Look at the Volume History',
            body: "A stock that normally trades 50,000 shares per day suddenly seeing 5 million is a major signal. Real organic growth doesn't usually look like that. Ask: why now, why so sudden?",
          },
          {
            type: 'tap-reveal',
            emoji: '🛡️',
            heading: 'How to Protect Yourself',
            body: 'Tap for the simple rule that keeps you out of traps.',
            tapReveal: "Before buying anything being hyped: (1) Google the company — real financials, real products? (2) Check how long it's been publicly listed. (3) Ask who profits if you buy. If someone is aggressively telling you to buy — they're probably already in and need you to move their price.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Spot the Trap',
            quiz: {
              question: "A stock you've never heard of suddenly appears everywhere on social media. It's up 80% in two days on a small company with no recent news. What's most likely happening?",
              options: [
                'A genuine breakout based on company fundamentals',
                "It's probably a pump and dump scheme",
                'This always signals a good long-term investment',
                'You should buy immediately before you miss out',
              ],
              correctIndex: 1,
              explanation: "This is a textbook pump and dump setup. The 'fear of missing out' is exactly what manipulators want you to feel. Sudden spike + no real news + heavy social promotion = the warning pattern.",
            },
          },
          {
            type: 'complete',
            emoji: '🔒',
            heading: 'Scam-Proof',
            body: 'You now recognize manipulation tactics. That protects your money better than any indicator.',
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv2-l5',
        title: 'Timing & Risk Unit Quiz',
        emoji: '📝',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '📝',
            heading: 'Unit 2 Quiz',
            body: "Let's lock in everything from timing, risk management, and smart defense.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "You have a $3,000 account. The 1% rule says you should risk no more than how much per trade?",
              options: ['$300', '$30', '$150', '$600'],
              correctIndex: 1,
              explanation: '1% of $3,000 = $30. Keeping risk small per trade ensures a losing streak never wipes you out before you can learn and improve.',
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: 'What is the purpose of a stop loss?',
              options: [
                'To guarantee a profit',
                'To automatically exit a losing trade before losses grow',
                'To buy more shares when the price drops',
                'To predict future price movements',
              ],
              correctIndex: 1,
              explanation: 'A stop loss is a pre-set exit point. It removes emotion from the decision and caps your maximum loss on any position.',
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: 'Which is a classic warning sign of a pump and dump scheme?',
              options: [
                'The company just released strong quarterly earnings',
                'A major fund just bought a large stake',
                'Unknown social media accounts are aggressively promoting an obscure stock',
                'The stock has been rising slowly over 6 months',
              ],
              correctIndex: 2,
              explanation: "Aggressive, coordinated social media promotion of obscure, low-liquidity stocks is a hallmark pump and dump pattern. Legitimate investments don't need influencer campaigns.",
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Unit 2 Complete!',
            body: 'Risk management, stop losses, and scam recognition — you\'re building real trader discipline.',
            xpReward: 20,
          },
        ],
      },
    ],
  },
  {
    id: 'lv3',
    title: 'The Full Picture',
    subtitle: 'Earnings, market cycles, and building your strategy.',
    color: 'bg-red-500/10',
    borderColor: 'border-red-400',
    lessons: [
      {
        id: 'lv3-l1',
        title: 'Reading Earnings Reports',
        emoji: '📋',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '📋',
            heading: 'What the Company Is Actually Saying',
            body: "Every quarter, public companies release earnings reports — their financial report card. This is where fundamentals meet price movement. Learning to read them gives you a real edge.",
          },
          {
            type: 'text',
            emoji: '💰',
            heading: 'Revenue vs. Earnings',
            body: "Revenue is how much money the company brought in. Earnings (net income) is what's left after expenses. A company can have massive revenue and still be losing money — knowing the difference matters.",
          },
          {
            type: 'text',
            emoji: '🎯',
            heading: 'Beating the Estimate',
            body: "Analysts predict how much a company will earn each quarter. The stock price often moves not based on the raw number — but on whether the company beat or missed that estimate. This is called \"beating the street.\"",
          },
          {
            type: 'fact',
            emoji: '📉',
            heading: 'Buy the Rumor, Sell the News',
            body: "Sometimes a company beats earnings and the stock still drops. Why? Traders already bought in anticipation. Once the news is out, they sell to lock in gains. This pattern is so common it has a name: \"buy the rumor, sell the news.\"",
          },
          {
            type: 'tap-reveal',
            emoji: '🔑',
            heading: 'What to Actually Look For',
            body: 'Tap to see the 3 numbers that matter most in an earnings report.',
            tapReveal: "(1) EPS (Earnings Per Share) — did they beat the estimate? (2) Revenue guidance — is the company projecting growth ahead? (3) Operating margin — are they becoming more or less profitable over time? These three paint the real picture.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Earnings Report Check',
            quiz: {
              question: "A company reports great earnings, but the stock drops 5%. What's the most likely reason?",
              options: [
                'The earnings report was fabricated',
                'Traders already priced in the good news and are now selling',
                'The company must have also announced a dividend cut',
                'The CEO sold shares',
              ],
              correctIndex: 1,
              explanation: '"Buy the rumor, sell the news" is real. Traders anticipate good earnings and buy beforehand. When the results confirm it, they sell — sending the price down even after a strong report.',
            },
          },
          {
            type: 'complete',
            emoji: '📊',
            heading: 'Earnings Decoded',
            body: 'You can now look past the headlines and understand what earnings reports actually mean for price.',
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv3-l2',
        title: 'Market Cycles',
        emoji: '🔄',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🔄',
            heading: 'The Market Moves in Cycles',
            body: "Markets don't go up forever, and they don't stay down forever. Understanding where we are in the cycle helps you make smarter decisions — instead of panicking at the wrong moment.",
          },
          {
            type: 'text',
            emoji: '🚀',
            heading: 'Accumulation Phase',
            body: "After a market bottom, smart money quietly starts buying. Prices are low, news is still bad, most people are fearful. This is where the real opportunity lives — but it takes courage and patience to act.",
          },
          {
            type: 'text',
            emoji: '📈',
            heading: 'Markup Phase (The Bull Run)',
            body: "Prices start rising, more people notice, media coverage picks up. The general public starts buying. This is the longest and most profitable phase for those who entered early.",
          },
          {
            type: 'text',
            emoji: '🏔️',
            heading: 'Distribution Phase',
            body: "At the top, smart money starts selling to the enthusiastic public. Prices plateau. Everyone is saying \"this time it's different.\" It rarely is.",
          },
          {
            type: 'fact',
            emoji: '💡',
            heading: 'The Pattern Repeats',
            body: "Markup → Distribution → Markdown (bear market) → Accumulation → Markup again. This cycle has repeated throughout market history. You can't time it perfectly — but knowing it helps you avoid the biggest mistakes.",
          },
          {
            type: 'chart-demo',
            demoType: 'bull-bear',
            emoji: '📈',
            heading: 'The Full Cycle Visualized',
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Cycle Check',
            quiz: {
              question: "Everyone you know is excited about stocks and media coverage is overwhelmingly positive. Which market phase does this suggest?",
              options: [
                'Accumulation — great time to buy',
                'Distribution — smart money may be selling to you',
                'Early markup — the rally is just starting',
                'Markdown — prices are about to recover',
              ],
              correctIndex: 1,
              explanation: "When the general public is euphoric and every headline is bullish, it often signals the distribution phase — where early investors are selling to late buyers. Maximum enthusiasm often coincides with market peaks.",
            },
          },
          {
            type: 'complete',
            emoji: '🌊',
            heading: 'Cycles Understood',
            body: 'You now see the bigger picture that most retail investors miss entirely.',
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv3-l3',
        title: 'Building Your Strategy',
        emoji: '🗺️',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🗺️',
            heading: 'Your Strategy, Your Life',
            body: "The best trading strategy is one you can actually follow consistently. Not someone else's system. Not what went viral online. One that fits your time, your personality, and your goals.",
          },
          {
            type: 'text',
            emoji: '📋',
            heading: 'Define Your Rules First',
            body: "Before your first real trade, write down: what you buy (criteria), when you buy (entry signal), when you sell if wrong (stop loss), and when you sell if right (take profit). A strategy with no rules is just gambling with extra steps.",
          },
          {
            type: 'text',
            emoji: '🧪',
            heading: 'Paper Trade Before You Risk Real Money',
            body: "Paper trading means practicing with fake money but real market prices. Most brokers offer this. You learn your system's strengths and weaknesses without losing a dollar.",
          },
          {
            type: 'fact',
            emoji: '📔',
            heading: 'Keep a Trade Journal',
            body: "Write down every trade: why you entered, what happened, what you felt. Your biggest source of improvement isn't a book or a course — it's your own patterns. You learn more from your own mistakes than anyone else's.",
          },
          {
            type: 'tap-reveal',
            emoji: '🎯',
            heading: 'The One Habit That Changes Everything',
            body: 'Tap to see what separates consistent traders from those who quit.',
            tapReveal: "Reviewing your trades weekly. Not to feel good or bad about results — but to ask: \"Did I follow my rules?\" A winning trade that broke your rules is dangerous. A losing trade that followed your rules is progress. Process beats outcome every time.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Strategy Thinking',
            quiz: {
              question: "You take a trade that loses $30, but you followed your rules perfectly. What does this mean?",
              options: [
                "Your strategy doesn't work and needs to be scrapped",
                "It's a normal outcome — losses are part of every good strategy",
                'You made a mistake and need to trade more aggressively to recover',
                'You should stop trading immediately',
              ],
              correctIndex: 1,
              explanation: "Even the best strategies have losing trades. What matters is whether you followed your rules. If you did, it's a good trade that happened to lose — and that's a completely acceptable outcome.",
            },
          },
          {
            type: 'complete',
            emoji: '🗺️',
            heading: 'Your Strategy Starts Here',
            body: 'You have the foundation. The real learning now happens through action, reflection, and consistency.',
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv3-l4',
        title: 'Everything Together',
        emoji: '🧩',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🧩',
            heading: 'Putting It All Together',
            body: "You've covered charts, risk, timing, earnings, and strategy. Let's connect it all into the complete picture of how a prepared trader actually thinks before placing a trade.",
          },
          {
            type: 'text',
            emoji: '🔭',
            heading: 'The Bigger Picture First',
            body: 'Start with market conditions. Is it a bull or bear environment? What phase are we in? This sets your default lean — toward being more aggressive or more cautious.',
          },
          {
            type: 'text',
            emoji: '🔬',
            heading: 'Then Zoom In on the Stock',
            body: "Look at the company's fundamentals. Is revenue growing? Did it recently beat earnings? Is the chart showing support holding or resistance breaking? All three lenses together give you real conviction.",
          },
          {
            type: 'fact',
            emoji: '⚖️',
            heading: 'Risk Before Reward',
            body: 'Every time you look at a trade idea, ask "how much can I lose?" before you ask "how much can I make?" Position sizing comes before anything else. Your survival depends on staying in the game long enough to compound your learning.',
          },
          {
            type: 'tap-reveal',
            emoji: '🏁',
            heading: 'The Pre-Trade Checklist',
            body: 'Tap to see the 5 questions every prepared trader asks before placing a trade.',
            tapReveal: "(1) Why am I buying this? (2) Where is my stop loss? (3) Where is my take profit? (4) How many shares based on my risk? (5) Does this fit my strategy rules? If you can't answer all five, the trade isn't ready.",
          },
          {
            type: 'complete',
            emoji: '🧩',
            heading: 'The Picture Is Complete',
            body: 'One more lesson and the Leveler track is yours.',
            xpReward: 15,
          },
        ],
      },
      {
        id: 'lv3-l5',
        title: 'Leveler Final Quiz',
        emoji: '🏆',
        xpReward: 30,
        slides: [
          {
            type: 'intro',
            emoji: '🏆',
            heading: 'Leveler Final Quiz',
            body: "Charts, risk, timing, earnings, cycles, strategy. Let's see how much you've built.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: 'A green candlestick with a very long lower wick means the price:',
              options: [
                'Dropped a lot, then recovered strongly by close',
                'Rose all day without any dips',
                'Opened and closed at the same price',
                'Was halted during trading',
              ],
              correctIndex: 0,
              explanation: "A long lower wick means the price dropped significantly during the period but buyers stepped in and pushed it back up. It's often a bullish signal — showing strong demand at lower prices.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: 'Your $4,000 account follows the 1% rule. You buy a stock at $80 with a stop at $76. How many shares can you buy?',
              options: ['5 shares', '10 shares', '20 shares', '50 shares'],
              correctIndex: 1,
              explanation: 'Max risk = 1% of $4,000 = $40. Risk per share = $80 − $76 = $4. Shares = $40 ÷ $4 = 10 shares.',
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: 'Which phase of the market cycle do most retail investors buy into?',
              options: [
                'Accumulation — when prices are cheapest',
                'Early markup — when the trend first starts',
                'Late markup and distribution — when excitement peaks',
                'Markdown — at the very bottom',
              ],
              correctIndex: 2,
              explanation: 'Most retail investors enter during peak enthusiasm — late markup into distribution. They buy because "everyone is making money," right before smart money is selling to them.',
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: 'What is the correct order for a disciplined trade setup?',
              options: [
                'Buy first, then decide your stop loss',
                'Define your stop loss and target before placing the trade',
                "Buy based on price action, sell based on how you feel",
                "Set a target first, figure out where you're wrong later",
              ],
              correctIndex: 1,
              explanation: 'Defining your stop loss and target before you enter removes emotion from both exits. Decide while you\'re calm — not while you\'re watching your money move.',
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Leveler Complete! 🎉',
            body: "You've done what most people never do — built a real foundation in technical analysis, risk management, and market psychology. Wealth Building is next.",
            xpReward: 30,
          },
        ],
      },
    ],
  },
]
