import type { Lesson, Unit } from '@/lib/starter-lessons'

export const OPTIONS_UNITS: Unit[] = [
  {
    id: 'op1',
    title: 'The Contract',
    subtitle: 'What you own, how to read the chain, and the two decisions that matter.',
    color: 'bg-blue-500/10',
    borderColor: 'border-blue-500',
    lessons: [
      {
        id: 'op1-l1',
        title: "What You're Actually Buying",
        emoji: '📄',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '📄',
            heading: "A Contract, Not a Stock",
            body: "When you buy a stock, you own a piece of a company. When you buy an option, you own a contract — a legal agreement that gives you the RIGHT, but not the obligation, to buy or sell 100 shares at a specific price before a specific date.",
          },
          {
            type: 'text',
            emoji: '📈',
            heading: 'A Call Option — The Right to Buy',
            body: "A call option gives you the right to BUY 100 shares at the strike price. You buy a call when you think the stock is going UP. If you're right, the call gains value. If you're wrong, you lose the premium you paid — nothing more.",
          },
          {
            type: 'text',
            emoji: '📉',
            heading: 'A Put Option — The Right to Sell',
            body: "A put option gives you the right to SELL 100 shares at the strike price. You buy a put when you think the stock is going DOWN. Puts make money when prices fall — which means you can profit in a bear market.",
          },
          {
            type: 'fact',
            emoji: '💵',
            heading: 'The Premium Is Your Max Loss',
            body: "You pay a premium to own the contract. One contract controls 100 shares, so if the premium is $3.00, you pay $300 (3.00 × 100). That $300 is the absolute most you can lose — unlike shorting a stock, your downside is always capped at what you paid.",
          },
          {
            type: 'tap-reveal',
            emoji: '🧪',
            heading: 'A Real Example',
            body: 'Tap to see how a call option actually plays out.',
            tapReveal: "Apple is at $200. You buy 1 call with a $205 strike for $3.00 ($300 total). If Apple rises to $220 before expiration, your contract is worth at least $15.00 ($1,500). You made $1,200 on $300 — a 400% return. If Apple stays flat or drops, your contract expires worthless. You lost $300. That's the trade.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Contract Check',
            quiz: {
              question: "You buy 1 call option for $2.50. How much did you actually spend, and what is your maximum possible loss?",
              options: [
                '$2.50 spent, unlimited loss potential',
                '$250 spent, maximum loss is $250',
                '$25 spent, maximum loss is $25',
                '$2.50 spent, maximum loss is $2.50',
              ],
              correctIndex: 1,
              explanation: "One contract controls 100 shares. $2.50 premium × 100 = $250 spent. Your maximum loss is exactly $250 — the premium you paid. Options buyers have defined, limited downside. That's one of their key advantages.",
            },
          },
          {
            type: 'complete',
            emoji: '📄',
            heading: 'Contract Understood',
            body: "Calls go up when the stock goes up. Puts go up when the stock goes down. Premium paid = max loss. You now have the foundation.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op1-l2',
        title: 'Reading the Options Chain',
        emoji: '🔗',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '🔗',
            heading: 'The Options Chain Is the Menu',
            body: "The options chain shows every available contract for a stock — organized by expiration date and strike price. Learning to read it quickly is one of the most important practical skills in options trading.",
          },
          {
            type: 'text',
            emoji: '📊',
            heading: 'How It Is Organized',
            body: "The chain is split in two: calls on the left, puts on the right. Down the middle is the strike price. Each row is a different strike. Calls and puts at the same strike are called a 'pair.' You pick which side and which row based on your trade.",
          },
          {
            type: 'text',
            emoji: '💰',
            heading: 'Bid, Ask, and Last',
            body: "Bid: what someone will pay you if you sell. Ask: what someone wants if you buy. Last: the most recent trade price. You almost always BUY at the ask and SELL at the bid. The difference (the spread) is a real cost — wide spreads on illiquid options eat into your profits before you start.",
          },
          {
            type: 'fact',
            emoji: '📋',
            heading: 'Volume and Open Interest',
            body: "Volume = contracts traded today. Open Interest = all active contracts that exist. Always trade options with high volume and open interest — at least 100 open interest, ideally 500+. Low liquidity means wide spreads and difficulty exiting at a fair price.",
          },
          {
            type: 'chart-demo',
            demoType: 'options-chain',
            emoji: '🔗',
            heading: 'Read a Live Chain',
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Chain Check',
            quiz: {
              question: "You want to buy a call option. The bid is $1.80 and the ask is $2.20. What price will you most likely pay?",
              options: [
                '$1.80 — always buy at the bid',
                '$2.00 — split the difference',
                '$2.20 — buyers pay the ask',
                'Whatever the last price was',
              ],
              correctIndex: 2,
              explanation: "When buying options, you pay the ask price. The bid is what a buyer will pay you when you SELL. The spread between bid and ask ($0.40 in this case = $40 per contract) is a real cost that comes out of your profit before the stock even moves.",
            },
          },
          {
            type: 'complete',
            emoji: '🔗',
            heading: 'Chain Decoded',
            body: "You can now read any options chain — calls, puts, strikes, bid/ask, volume. That's the menu. Next: what to order.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op1-l3',
        title: 'Strike Price + Expiration',
        emoji: '🎯',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '🎯',
            heading: 'Two Decisions That Define Every Options Trade',
            body: "When you buy an option, you make two decisions: which strike price, and which expiration date. These two choices determine your cost, your probability of profit, and how much time you have to be right.",
          },
          {
            type: 'text',
            emoji: '🏹',
            heading: 'Choosing Your Strike Price',
            body: "The strike price is the price you have the right to buy (call) or sell (put) the stock at. Lower call strikes are closer to the money — higher probability of profit but more expensive. Higher call strikes are farther out — cheaper but need bigger moves to pay off.",
          },
          {
            type: 'fact',
            emoji: '📏',
            heading: 'The Practical Starting Point',
            body: "For most trades, start with the at-the-money (ATM) strike or one strike out-of-the-money (OTM). ATM options have the most liquidity, balanced risk/reward, and delta around 0.50. Far OTM options are cheap but win rarely — they're lottery tickets.",
          },
          {
            type: 'text',
            emoji: '📅',
            heading: 'Choosing Your Expiration',
            body: "Expiration is when the contract dies. Short expirations (under 14 days) are cheap but dangerous — time decay is brutal and there's almost no room for error. For learning, use 30–60 days to expiration (DTE) minimum. It gives your thesis time to play out.",
          },
          {
            type: 'tap-reveal',
            emoji: '⚖️',
            heading: 'The Risk/Reward Tradeoff',
            body: 'Tap to see how strike and expiration affect what you pay vs what you can make.',
            tapReveal: "OTM + short expiration = cheapest option, lowest probability, highest % gain if right. ITM + longer expiration = most expensive, highest probability, lower % gain but more reliable. Neither is universally better — it depends on your conviction level and how far you think the stock will move.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Strike + Expiration',
            quiz: {
              question: "You're learning options and want to make your first trade. Which expiration is most appropriate to start with?",
              options: [
                '2 days to expiration — cheap and exciting',
                '7 days to expiration — gives one week for the move',
                '45 days to expiration — enough time for your thesis to develop',
                'Always pick the longest possible expiration',
              ],
              correctIndex: 2,
              explanation: "45 DTE gives your trade room to breathe. Time decay is manageable, you can exit early if right, and you're not immediately fighting the clock. Short-dated options are fine once you're experienced — but for learning, time is your friend.",
            },
          },
          {
            type: 'complete',
            emoji: '🎯',
            heading: "Two Decisions Made",
            body: "Strike determines your target. Expiration determines your runway. Choose both with intention.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op1-l4',
        title: 'ITM, ATM, and OTM',
        emoji: '🗺️',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '🗺️',
            heading: 'Where Your Strike Lives Relative to the Stock',
            body: "In the Money, At the Money, Out of the Money — these three terms describe where a strike price sits relative to the current stock price. Understanding them changes how you read every single option you'll ever look at.",
          },
          {
            type: 'text',
            emoji: '✅',
            heading: 'In the Money (ITM)',
            body: "A call is ITM when the stock price is ABOVE the strike. You already have the right to buy below market price — the option has real, immediate value called intrinsic value. ITM options are expensive but move more reliably with the stock.",
          },
          {
            type: 'text',
            emoji: '➡️',
            heading: 'At the Money (ATM)',
            body: "A call is ATM when the strike price is roughly equal to the current stock price. No intrinsic value yet, but highest sensitivity to price movement. ATM options have a delta of about 0.50 — a $1 move in the stock creates about a $0.50 move in the option.",
          },
          {
            type: 'text',
            emoji: '⚠️',
            heading: 'Out of the Money (OTM)',
            body: "A call is OTM when the stock price is BELOW the strike. The stock hasn't reached your target yet — this option has no intrinsic value, only time value. OTM options are cheap and can pay off big, but most expire worthless. Lower delta, lower probability.",
          },
          {
            type: 'fact',
            emoji: '📊',
            heading: 'Delta as a Probability Estimate',
            body: "Delta also approximates the probability of finishing ITM. A 0.30 delta (30%) call has roughly a 30% chance of being profitable at expiration. A 0.70 delta (70%) call is already well ITM and has a much higher probability. Higher delta = higher cost, higher confidence.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Money Check',
            quiz: {
              question: "A stock is trading at $55. You own a call with a $50 strike. Where is this option?",
              options: [
                'Out of the Money — the stock needs to fall to $50',
                'At the Money — the prices are close enough',
                'In the Money — the stock is above the strike',
                "It depends on the expiration date",
              ],
              correctIndex: 2,
              explanation: "With the stock at $55 and your strike at $50, you have the right to buy at $50 — which is $5 below the current market price. That $5 is intrinsic value. This call is In the Money.",
            },
          },
          {
            type: 'complete',
            emoji: '🗺️',
            heading: 'Mapped',
            body: "ITM = already has value. ATM = at the tipping point. OTM = needs to move your way. Now you speak the language fluently.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op1-l5',
        title: 'The Contract — Unit Quiz',
        emoji: '📝',
        xpReward: 25,
        slides: [
          {
            type: 'intro',
            emoji: '📝',
            heading: 'Unit 1 Quiz',
            body: "Calls, puts, the chain, strike price, expiration, ITM/OTM. Lock it in.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "You buy 2 put contracts for $1.50 each. How much did you spend total?",
              options: ['$3.00', '$150', '$300', '$1.50'],
              correctIndex: 2,
              explanation: "Each contract controls 100 shares. $1.50 × 100 = $150 per contract. 2 contracts = $300. This is also your maximum total loss — puts have defined downside equal to the premium paid.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "A stock is at $100. You're looking at calls. Which strike is Out of the Money?",
              options: ['$95 strike', '$100 strike', '$110 strike', 'All strikes are OTM'],
              correctIndex: 2,
              explanation: "A call is OTM when the strike is ABOVE the current stock price. The $110 strike means the stock needs to rise above $110 before your call has intrinsic value. $95 would be ITM (stock above strike). $100 would be ATM.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "When buying options, why does high open interest matter?",
              options: [
                'It means the option is guaranteed to be profitable',
                'High open interest indicates a liquid market with tighter bid/ask spreads',
                'It means the stock is more likely to move in your direction',
                "Open interest doesn't affect options traders",
              ],
              correctIndex: 1,
              explanation: "High open interest means many contracts are active — which means more buyers and sellers, tighter spreads, and easier exits at fair prices. Illiquid options with low open interest have wide spreads that silently destroy your returns.",
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Unit 1 Complete!',
            body: "You understand what an option is, how to read the chain, and the key terms. The mechanics are locked in.",
            xpReward: 25,
          },
        ],
      },
    ],
  },
  {
    id: 'op2',
    title: 'The Greeks',
    subtitle: "Delta, theta, and IV — the three forces that move your option's price.",
    color: 'bg-brand-purple/20',
    borderColor: 'border-brand-purple',
    lessons: [
      {
        id: 'op2-l1',
        title: 'Delta — Your Directional Exposure',
        emoji: 'Δ',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '📐',
            heading: 'Delta: How Much You Move With the Stock',
            body: "Delta tells you how much your option's price changes when the stock moves $1. It's the most important Greek to understand because it directly determines your profit and loss on every move the stock makes.",
          },
          {
            type: 'text',
            emoji: '📈',
            heading: 'How Delta Works',
            body: "A call option with delta 0.50 gains $0.50 for every $1 the stock goes up — and loses $0.50 for every $1 it goes down. Delta 0.70 = $0.70 per $1 move. Delta 0.25 = $0.25 per $1 move. One contract = 100 shares, so delta 0.50 on one contract = $50 gain/loss per $1 stock move.",
          },
          {
            type: 'fact',
            emoji: '🎯',
            heading: 'Delta Also Tells You Probability',
            body: "A 0.30 delta option has roughly a 30% chance of finishing In the Money at expiration. A 0.70 delta option has about a 70% chance. This is why higher delta options cost more — you're paying for higher probability.",
          },
          {
            type: 'text',
            emoji: '↕️',
            heading: 'Delta Changes as the Stock Moves',
            body: "Delta isn't fixed. As the stock moves up, a call's delta increases (toward 1.0). As the stock moves down, delta decreases (toward 0). This acceleration is called gamma — which you'll learn next unit. For now: winning options get more powerful as they move your way.",
          },
          {
            type: 'tap-reveal',
            emoji: '💡',
            heading: "The Practical Takeaway",
            body: 'Tap to see how traders use delta to choose their strike.',
            tapReveal: "High delta (0.70+): you move almost dollar-for-dollar with the stock. Lower risk of going to zero, but expensive. Good for high-confidence, lower-reward trades. Low delta (0.20-0.35): cheap, but needs a big move to pay off. Good when you expect a large move. ATM (delta ~0.50): balanced. Best starting point for most trades.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Delta Check',
            quiz: {
              question: "You own 1 call contract with delta 0.40. The stock moves up $3. How much did your option gain?",
              options: ['$0.40', '$40', '$120', '$300'],
              correctIndex: 2,
              explanation: "Delta 0.40 × $3 move = $1.20 gain per share. One contract = 100 shares. $1.20 × 100 = $120 gain. If delta had been 0.70, the gain would have been $210. Higher delta = more sensitive to price moves.",
            },
          },
          {
            type: 'complete',
            emoji: '📐',
            heading: 'Delta Understood',
            body: "Delta is your speedometer — it tells you how fast your option moves with the stock. Know it before every trade.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op2-l2',
        title: 'Theta — Time Is Your Enemy',
        emoji: 'Θ',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '⏳',
            heading: 'Every Day You Hold, You Lose Money',
            body: "Theta is the cost of holding an option. Every single day that passes, your option loses value — even if the stock doesn't move at all. This is called time decay. It's the single biggest reason beginner options traders lose money.",
          },
          {
            type: 'text',
            emoji: '📉',
            heading: 'What Theta Looks Like in Numbers',
            body: "If your option has theta of -0.05, it loses $0.05 per share per day — that's $5 per contract per day. An option with theta -0.10 loses $10 per contract per day. Doesn't sound like much until you've held for 3 weeks and lost $150 to time alone.",
          },
          {
            type: 'fact',
            emoji: '🚨',
            heading: 'Decay Accelerates Near Expiration',
            body: "Theta is not linear. An option with 60 DTE decays slowly. With 30 DTE, decay picks up. With 14 DTE, it accelerates sharply. With 7 DTE, it's brutal. The last two weeks of an option's life, time value evaporates fastest — this is why holding through expiration hoping for a miracle rarely works.",
          },
          {
            type: 'chart-demo',
            demoType: 'theta-decay',
            emoji: '⏳',
            heading: 'Watch Time Decay in Action',
          },
          {
            type: 'tap-reveal',
            emoji: '🛡️',
            heading: 'How to Fight Theta',
            body: 'Tap to see the two strategies traders use against time decay.',
            tapReveal: "Strategy 1: Buy enough time. 45-60 DTE gives your thesis time to play out before decay accelerates. Strategy 2: Take profits early. If your option gains 25-50%, close it. You don't need to hold to expiration — and most experienced traders don't. Closing at 50% profit with 30 DTE left is almost always smarter than holding for more.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Theta Check',
            quiz: {
              question: "You buy an option for $200 with theta of -0.08. The stock stays completely flat for 10 days. What is your option approximately worth now?",
              options: ['$200 — it only changes when the stock moves', '$192', '$120', '$280'],
              correctIndex: 2,
              explanation: "Theta -0.08 × 100 shares = $8 lost per day. Over 10 days = $80 lost to time decay alone. $200 − $80 = $120. This is why flat stocks still hurt options buyers. Time is always working against you when you own options.",
            },
          },
          {
            type: 'complete',
            emoji: '⏳',
            heading: 'Theta Respected',
            body: "Time decay is the silent killer of options positions. Now you know to fight it — buy enough time, and take profits before the clock runs out.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op2-l3',
        title: 'Implied Volatility — The Hidden Price Driver',
        emoji: 'σ',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '🌪️',
            heading: 'IV Is What You Pay For Uncertainty',
            body: "Implied Volatility (IV) is the market's expectation of how much a stock will move. High IV = the market expects big swings. Low IV = stability expected. IV directly inflates or deflates option prices — independent of the stock's direction.",
          },
          {
            type: 'text',
            emoji: '💸',
            heading: 'Why IV Matters to Buyers',
            body: "When IV is high, options are expensive — you pay more premium for the same strike and expiration. When IV is low, options are cheap. Smart options buyers look for low IV environments to buy options, and high IV environments to sell them.",
          },
          {
            type: 'fact',
            emoji: '💥',
            heading: 'IV Crush — The Most Common Beginner Trap',
            body: "Before earnings, IV spikes as everyone buys options speculating on the move. After the announcement — even if the stock moves in your direction — IV collapses instantly. This is called IV crush. An option can lose 30-50% of its value in minutes after earnings even when the stock moves the right way.",
          },
          {
            type: 'text',
            emoji: '📊',
            heading: 'IV Rank and IV Percentile',
            body: "Don't look at IV in isolation. IV Rank tells you where today's IV sits relative to the past year. IV Rank of 80 = IV is near its highest point in a year — options are expensive. IV Rank of 20 = options are cheap historically. Always check IV Rank before buying.",
          },
          {
            type: 'tap-reveal',
            emoji: '🎓',
            heading: 'The Rule That Protects Beginners',
            body: 'Tap for the simplest IV rule to follow.',
            tapReveal: "Avoid buying options with less than 7 days to earnings. IV will be elevated and even a correct directional guess can lose money to IV crush. If you want to trade earnings, buy your options 2-3 weeks before the announcement when IV is still building — then close before the news hits. Collect the IV expansion, not the IV collapse.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'IV Check',
            quiz: {
              question: "A stock reports earnings and jumps 8% — exactly what you predicted. But your call option lost 20% in value. What most likely happened?",
              options: [
                'You made a calculation error',
                'The stock movement was not enough',
                'IV crush collapsed the option price despite the correct directional move',
                'Your broker made a mistake',
              ],
              correctIndex: 2,
              explanation: "IV crush is real and common. The pre-earnings IV spike inflated your option price. When the news dropped, IV collapsed — even with an 8% upward move, the IV crush overwhelmed the directional gain. This is why experienced traders close options BEFORE earnings announcements.",
            },
          },
          {
            type: 'complete',
            emoji: '🌪️',
            heading: 'IV Unlocked',
            body: "IV makes options expensive or cheap independent of direction. Buy when IV is low, avoid buying right before earnings. This alone puts you ahead of most beginners.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op2-l4',
        title: 'Gamma, Vega & Putting It Together',
        emoji: '⚡',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '⚡',
            heading: 'The Last Two Greeks You Need',
            body: "Delta and theta will drive most of your options thinking. Gamma and vega show up in specific situations — and when they do, they're powerful. Here's what to know.",
          },
          {
            type: 'text',
            emoji: '🔄',
            heading: 'Gamma — The Accelerator',
            body: "Gamma measures how fast delta changes. ATM options have the highest gamma — small stock moves create rapidly changing delta. Near expiration, gamma becomes extreme. A 0.01 stock move in the last hour of a 0DTE option can swing the P&L wildly. Gamma is what makes short-dated options explosive.",
          },
          {
            type: 'text',
            emoji: '📡',
            heading: 'Vega — IV Sensitivity',
            body: "Vega measures how much an option gains or loses for every 1% change in IV. Long-dated options have high vega — they benefit when IV rises and get hurt when IV falls. If you buy a 90-DTE option and IV drops, vega can cause significant losses even if the stock moves your way.",
          },
          {
            type: 'fact',
            emoji: '🗺️',
            heading: 'How They All Work Together',
            body: "Every option trade is a combination of forces: delta (direction), theta (time decay against you), vega (IV changes), and gamma (acceleration). A good trade needs direction AND timing AND IV on your side. This is why options require more precision than stocks.",
          },
          {
            type: 'tap-reveal',
            emoji: '📋',
            heading: 'The Pre-Trade Greeks Checklist',
            body: 'Tap to see what to check before every options entry.',
            tapReveal: "Delta: is my strike giving me meaningful exposure? (aim for 0.40-0.60 ATM or 0.25-0.40 for OTM). Theta: how much am I losing per day if nothing moves? (check it's manageable). IV Rank: is IV high or low right now? (prefer low IV for buying). Gamma: is expiration near enough to create dangerous swings? (avoid <14 DTE until experienced).",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Greeks Final',
            quiz: {
              question: "You're buying a call with 5 days to expiration. Which risk is most dangerous in this situation?",
              options: [
                "Delta — the option won't move with the stock",
                'Theta — time decay is now extremely aggressive',
                'Vega — IV will crush the option',
                "Gamma — it won't be high enough to matter",
              ],
              correctIndex: 1,
              explanation: "With only 5 DTE, theta is in its most aggressive phase. Time value evaporates rapidly — even a correct directional move can be overwhelmed by a single day of theta. Short-dated options are for experienced traders who understand this tradeoff.",
            },
          },
          {
            type: 'complete',
            emoji: '⚡',
            heading: 'Greeks Complete',
            body: "Delta, theta, IV, gamma, vega. You now understand every force that moves your option's price. Most traders never fully learn this. You have.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op2-l5',
        title: 'The Greeks — Unit Quiz',
        emoji: '📝',
        xpReward: 25,
        slides: [
          {
            type: 'intro',
            emoji: '📝',
            heading: 'Unit 2 Quiz',
            body: "Delta, theta, IV, gamma, vega. Let's see what stuck.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "You own 2 call contracts with delta 0.55. The stock drops $2. What happens to your position?",
              options: [
                'Gains $220',
                'Loses $110',
                'Loses $220',
                'Nothing — puts are affected by stock drops, not calls',
              ],
              correctIndex: 2,
              explanation: "Delta 0.55 × $2 drop = $1.10 loss per share. One contract = 100 shares. $1.10 × 100 = $110 per contract. 2 contracts = $220 loss. Calls lose value when the stock drops — delta works in both directions.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "IV Rank is currently at 85 for a stock you want to buy calls on. What does this mean for you?",
              options: [
                "Great time to buy — options are cheap",
                "Options are near their most expensive level of the past year — buying is risky",
                "IV Rank doesn't affect call buyers",
                "You should buy puts instead",
              ],
              correctIndex: 1,
              explanation: "IV Rank of 85 means IV is in the 85th percentile of the past year — options are near their most expensive. Buying options in high IV environments means you're overpaying for premium. If IV reverts lower (even if the stock moves your way), you can lose money.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "The best time to buy options is when:",
              options: [
                'IV is high and earnings are tomorrow',
                'IV is low and you have a clear directional thesis',
                'Theta is at its highest (near expiration)',
                'Open interest is low on the strike you want',
              ],
              correctIndex: 1,
              explanation: "Low IV = cheap options. A clear directional thesis = logical reason to be in the trade. Together: you're not overpaying for the contract AND you have a reason to be bullish or bearish. That's the foundation of a good options entry.",
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Unit 2 Complete!',
            body: "The Greeks are the engine under the hood. You now understand what actually moves your option's price — beyond just the stock going up or down.",
            xpReward: 25,
          },
        ],
      },
    ],
  },
  {
    id: 'op3',
    title: 'Entries & Exits',
    subtitle: 'When to get in, when to get out, and how to size every trade.',
    color: 'bg-brand-green/10',
    borderColor: 'border-brand-green',
    lessons: [
      {
        id: 'op3-l1',
        title: 'Buying Calls — The Bullish Play',
        emoji: '📈',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '📈',
            heading: 'Calls Are Your Weapon in an Uptrend',
            body: "A call option profits when a stock goes up. But buying calls randomly on stocks you like is not a strategy — it's gambling. Here's the actual framework for finding and entering quality call setups.",
          },
          {
            type: 'text',
            emoji: '✅',
            heading: 'The Call Entry Checklist',
            body: "Before buying a call: (1) Stock is in an uptrend or breaking out. (2) Chart shows a clear setup — bounce off support, breakout from consolidation. (3) Volume confirms the move. (4) IV Rank is not elevated. (5) You have 30+ DTE. Every item should check out — not just one.",
          },
          {
            type: 'text',
            emoji: '🎯',
            heading: 'Choosing the Right Strike',
            body: "For most calls: start with ATM (delta ~0.50) or one strike OTM (delta ~0.35). ATM if you want higher probability. OTM if you expect a larger move and want more leverage. Avoid going more than 2 strikes OTM — probability drops sharply and you need a huge move to win.",
          },
          {
            type: 'fact',
            emoji: '📍',
            heading: 'The Entry Trigger',
            body: "Don't buy a call just because a stock looks good. Wait for a specific, defined trigger: a break above resistance with volume, a bounce off support with a confirming candle, or a gap above a moving average. The trigger is the moment your thesis becomes actionable.",
          },
          {
            type: 'tap-reveal',
            emoji: '🧪',
            heading: 'A Full Call Setup Example',
            body: 'Tap to walk through a real call trade from setup to entry.',
            tapReveal: "Stock: $NVDA. Trend: uptrend on daily chart. Setup: pulled back to 50-day moving average, bouncing with volume. IV Rank: 22 (low). Trade: buy the ATM call (nearest strike to current price) with 45 DTE. Risk: 1% of account (premium paid = max loss). Target: 50% gain on the option. Stop: exit if option loses 50% of premium.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Call Setup Check',
            quiz: {
              question: "A stock you like is in a clear uptrend but IV Rank is 78. What should you do?",
              options: [
                'Buy the call immediately — the trend is strong',
                'Wait for IV to come down before buying, or skip this trade',
                'Buy a longer expiration to compensate for high IV',
                'Buy puts instead',
              ],
              correctIndex: 1,
              explanation: "High IV means you're overpaying for the option. Even in a strong uptrend, if IV comes down after you buy, vega losses can offset directional gains. Patience — wait for IV to normalize, or find another setup where the risk/reward is cleaner.",
            },
          },
          {
            type: 'complete',
            emoji: '📈',
            heading: 'Calls Mastered',
            body: "Trend + setup + trigger + low IV + defined risk. That's a real call trade, not a guess.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op3-l2',
        title: 'Buying Puts — The Bearish Play',
        emoji: '📉',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '📉',
            heading: "Profit When Stocks Fall",
            body: "Most people only know how to make money when stocks go up. Options give you a weapon for downtrends too. A put option gains value when the stock drops — and applying the same disciplined framework makes them just as tradeable as calls.",
          },
          {
            type: 'text',
            emoji: '🔄',
            heading: 'Puts Are the Mirror Image of Calls',
            body: "Everything you learned about calls applies to puts in reverse. A put is OTM when stock price is ABOVE the strike. A put gains value as the stock falls. Delta on puts is negative (-0.50 ATM) — a $1 drop in the stock gains you $0.50 per share on an ATM put.",
          },
          {
            type: 'text',
            emoji: '✅',
            heading: 'The Put Entry Checklist',
            body: "(1) Stock is in a downtrend or breaking below support. (2) Clear trigger — break below support with volume, rejection at resistance. (3) Overall market is weak or neutral (puts are harder in bull markets). (4) IV Rank is not elevated. (5) 30+ DTE. Same discipline, opposite direction.",
          },
          {
            type: 'fact',
            emoji: '🛡️',
            heading: 'Puts as Portfolio Insurance',
            body: "Experienced traders also use puts to hedge. If you own 100 shares of a stock and are worried about a short-term drop, buying a put acts like insurance — if the stock drops, your put gains, offsetting the stock loss. This is called a protective put.",
          },
          {
            type: 'tap-reveal',
            emoji: '⚠️',
            heading: "The Put Trap to Avoid",
            body: 'Tap to see the most common put buying mistake.',
            tapReveal: "Buying puts in a bull market because 'it can't go higher.' Markets can stay irrational longer than your option can survive theta. Puts work best when the trend is already down or a clear breakdown is in progress — not as bets against strength. Trade what's in front of you, not what you think should happen.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Put Setup',
            quiz: {
              question: "A stock breaks below a major support level on high volume. This is most clearly a setup for:",
              options: [
                'Buying a call — the breakdown will reverse',
                'Buying a put — the breakdown confirms downside momentum',
                'Doing nothing — breakdowns are always fake',
                'Buying the stock at discount',
              ],
              correctIndex: 1,
              explanation: "A break below support on high volume is a textbook bearish signal — it confirms sellers are in control. A put positioned just below that support level profits as the stock continues lower. Volume is the confirmation that makes this a real breakdown, not a fake-out.",
            },
          },
          {
            type: 'complete',
            emoji: '📉',
            heading: 'Puts in the Toolkit',
            body: "You can now profit in both directions. Uptrends, downtrends — the framework is the same. Only the direction changes.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op3-l3',
        title: 'Position Sizing for Options',
        emoji: '🧮',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '🧮',
            heading: 'The 1% Rule, Options Edition',
            body: "Position sizing with options works from the same foundation: never risk more than 1% of your account on a single trade. The difference is how you apply it — because options can go to zero, and 1% of a small account needs to be used wisely.",
          },
          {
            type: 'text',
            emoji: '💵',
            heading: 'Premium Paid = Your Max Risk',
            body: "The most you can lose on a long option is the premium you paid. So your 1% rule becomes: the total premium for any single trade should not exceed 1% of your account. $5,000 account → max $50 per options trade. $10,000 account → max $100 per options trade.",
          },
          {
            type: 'fact',
            emoji: '⚡',
            heading: 'The 50% Stop Loss Rule',
            body: "Most professional options traders set a 50% stop on premium paid. If your option drops to 50% of what you paid, exit — regardless of conviction. A $100 option that drops to $50: exit. You still have $50 to redeploy. Holding to zero is almost never the right move.",
          },
          {
            type: 'text',
            emoji: '🏆',
            heading: 'The 25-50% Profit Target',
            body: "Take 25-50% profit. Yes, it might go higher. But closing at 50% gain consistently across 100 trades outperforms holding for 100%+ and giving back profits. The traders who build accounts do so through consistency — not hero trades.",
          },
          {
            type: 'chart-demo',
            demoType: 'position-sizing',
            emoji: '🧮',
            heading: 'Size Your Options Trade',
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Options Sizing',
            quiz: {
              question: "You have a $3,000 account. Using the 1% rule, what is your max spend on a single options trade?",
              options: ['$300', '$30', '$150', '$3'],
              correctIndex: 1,
              explanation: "1% of $3,000 = $30. That means you can buy options that cost up to $30 in total premium per trade. At this account size, you're looking at cheap OTM options or very small positions. As the account grows, so does your position size.",
            },
          },
          {
            type: 'complete',
            emoji: '🧮',
            heading: 'Sizing Locked',
            body: "1% max premium. 50% stop. 25-50% profit target. These three rules run every single trade you place.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op3-l4',
        title: 'Managing the Trade',
        emoji: '🎮',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '🎮',
            heading: 'Getting In Is Easy. Staying Disciplined Is the Job.',
            body: "Most options traders know how to find setups. Where they lose money is in managing positions after they're in — holding losers too long, exiting winners too early, or letting emotions override the plan. Here's the system.",
          },
          {
            type: 'text',
            emoji: '🏁',
            heading: 'Define Your Exits Before You Enter',
            body: "Before placing any options trade, write down three things: (1) Your profit target — at what option price or % gain you'll close. (2) Your stop loss — the 50% premium rule, or a specific option price. (3) Your time stop — if you reach X DTE with no movement, exit.",
          },
          {
            type: 'text',
            emoji: '⏰',
            heading: 'The Time Stop',
            body: "If you bought a 45-DTE option and at 20 DTE it's still flat or slightly negative — exit. You're now in the dangerous theta acceleration zone and your thesis hasn't materialized. Exiting with 20-25 DTE left preserves remaining time value and lets you redeploy capital into a fresh setup.",
          },
          {
            type: 'fact',
            emoji: '🔁',
            heading: 'Never Hold Options to Expiration',
            body: "Options expire worthless all the time. Holding to expiration hoping for a last-minute move is how options traders lose 100% of their premium. If you haven't hit your target with 7 DTE remaining, close the position and move on. The next setup is always coming.",
          },
          {
            type: 'tap-reveal',
            emoji: '🧠',
            heading: 'The Mindset That Keeps Accounts Alive',
            body: 'Tap to hear the most important mental model for options trading.',
            tapReveal: "You will lose on options trades. Frequently. Even great options traders win 50-60% of the time — and they're still profitable because their winners are bigger than their losers. The goal is NOT to be right every time. The goal is to keep losses small (50% stop), take profits consistently (25-50% rule), and stay in the game long enough to let your edge compound.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Trade Management',
            quiz: {
              question: "You bought an option for $200. It's now worth $100 (50% loss) and you have 15 DTE remaining. What should you do?",
              options: [
                'Hold — it could recover in 15 days',
                'Buy more contracts to average down',
                'Close the position — the 50% stop rule says exit',
                'Wait until expiration to see the final result',
              ],
              correctIndex: 2,
              explanation: "Your 50% stop rule exists for this exact moment. Holding through a 50% loss hoping for recovery with 15 DTE means you're now fighting both a bad position AND accelerating theta. Exit with your remaining $100, preserve capital, and find the next setup.",
            },
          },
          {
            type: 'complete',
            emoji: '🎮',
            heading: 'Trade Management Built In',
            body: "Define exits before entry. Honor your stops. Exit losers early. Take profits consistently. This is what separates accounts that grow from accounts that blow up.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op3-l5',
        title: 'Entries & Exits — Unit Quiz',
        emoji: '📝',
        xpReward: 25,
        slides: [
          {
            type: 'intro',
            emoji: '📝',
            heading: 'Unit 3 Quiz',
            body: "Calls, puts, position sizing, and trade management. Let's see what you've got.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "A stock is breaking out above resistance on three times normal volume. IV Rank is 18. You have a bullish thesis. What's your move?",
              options: [
                'Buy a put — the breakout will fail',
                'Buy a call — trend, volume, and low IV all align',
                'Wait — breakouts always reverse',
                "Buy the stock instead since IV doesn't matter",
              ],
              correctIndex: 1,
              explanation: "This is a textbook call setup: directional momentum (breakout), volume confirmation, and low IV (cheap options). All three checkboxes are hit. A 30-45 DTE ATM or one-strike OTM call with 1% account risk is the play.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "You bought a call for $150. It's up 55% and worth $232.50. Based on the 25-50% profit rule, what should you consider doing?",
              options: [
                'Hold — it could reach 200%',
                'Add more contracts since it is working',
                'Take the profit — 55% exceeds your 25-50% target range',
                'Nothing until expiration',
              ],
              correctIndex: 2,
              explanation: "A 55% gain exceeds your 25-50% target. Close it. Locking in $82.50 profit on a $150 trade is an excellent result. The temptation to hold for more is exactly where most traders give back gains. Consistent 25-50% wins compound into serious returns over time.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "What is a 'time stop' in options trading?",
              options: [
                'A market order that only executes at a certain time of day',
                'Exiting a trade that has not moved after reaching a certain number of DTE remaining',
                'The expiration date printed on the contract',
                'A broker feature to pause trading',
              ],
              correctIndex: 1,
              explanation: "A time stop is a pre-defined rule: if your option hasn't moved in your favor by X DTE remaining, exit — regardless of P&L. It protects you from holding through the most dangerous theta acceleration zone near expiration.",
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Unit 3 Complete!',
            body: "You now have a complete entry and exit framework for options. Every trade has a plan before it starts.",
            xpReward: 25,
          },
        ],
      },
    ],
  },
  {
    id: 'op4',
    title: 'Real Strategy',
    subtitle: 'Trend trading, technical setups, earnings plays, and the wheel.',
    color: 'bg-red-500/10',
    borderColor: 'border-red-400',
    lessons: [
      {
        id: 'op4-l1',
        title: 'Trend Trading With Options',
        emoji: '🌊',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '🌊',
            heading: 'Trade With the Current, Not Against It',
            body: "The cleanest, most consistent options strategy is trend trading — using options to amplify your exposure to moves that are already in motion. The trend is your directional confirmation before you touch an options chain.",
          },
          {
            type: 'text',
            emoji: '📊',
            heading: 'Timeframe Alignment',
            body: "Use the weekly chart to determine the primary trend. Use the daily chart to time your entry. If the weekly is bullish (higher highs, higher lows) and the daily is pulling back to support, you have alignment. Buy the call on the daily bounce. The weekly keeps you on the right side.",
          },
          {
            type: 'text',
            emoji: '📍',
            heading: 'The Pullback Entry',
            body: "In an uptrend, stocks pull back before continuing. The ideal call entry is when a stock pulls back to a key level — 50-day moving average, previous support, trend line — then shows a reversal signal. You're buying the dip in an uptrend, not chasing the top.",
          },
          {
            type: 'fact',
            emoji: '🔁',
            heading: 'The Trend Trade Cycle',
            body: "Uptrend → pullback to support → bounce → buy call → stock resumes trend → close at 25-50% gain → wait for next pullback. This repeatable cycle, executed consistently with proper sizing, builds accounts steadily without needing to predict tops or bottoms.",
          },
          {
            type: 'tap-reveal',
            emoji: '🧭',
            heading: "What Kills Trend Trades",
            body: 'Tap to see the two biggest mistakes in trend trading with options.',
            tapReveal: "Mistake 1: Chasing. Buying a call after the stock has already moved 10% misses the entry — you're now buying at the top of the move with less room to run and more risk. Wait for the pullback. Mistake 2: Fighting the trend. If the weekly chart is bearish, don't buy calls because the daily looks ok. Always trade in the direction of the larger timeframe.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Trend Trade Setup',
            quiz: {
              question: "A stock's weekly chart shows a clear uptrend. On the daily chart it just touched the 50-day moving average and is bouncing. What does this represent?",
              options: [
                'A breakdown — exit all positions',
                'A trend change — the uptrend is ending',
                'A pullback entry opportunity — classic call setup',
                'A signal to buy puts',
              ],
              correctIndex: 2,
              explanation: "Pullback to the 50-day MA in an uptrend is a textbook entry point. The weekly confirms the trend is bullish. The daily shows the stock found support at a key level. A call bought here has both momentum and a defined risk level (stop below the 50-day MA).",
            },
          },
          {
            type: 'complete',
            emoji: '🌊',
            heading: 'Trend Framework Built',
            body: "Weekly for direction. Daily for entry. Pullback to support for timing. This framework works across every liquid stock and index.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op4-l2',
        title: 'Support, Resistance & Options',
        emoji: '🧲',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '🧲',
            heading: "Your Technical Analysis Now Has Leverage",
            body: "Everything you learned about support and resistance in the Leveler track directly applies to options entries. The levels you identify on the chart become the logic behind your strike and stop loss.",
          },
          {
            type: 'text',
            emoji: '📍',
            heading: 'Support as Your Call Entry',
            body: "When a stock approaches a strong support level — one it has bounced from multiple times — you're looking at a potential call entry. The support is your thesis: 'buyers have shown up here before, and I expect them to again.' Your stop: a close below support invalidates the trade.",
          },
          {
            type: 'text',
            emoji: '🚀',
            heading: 'Resistance Breakouts as Call Entries',
            body: "When a stock breaks above a major resistance level on volume, old resistance becomes new support. That breakout is a call entry — the market has just confirmed buyers are stronger than sellers at that level. Enter on the breakout, or on the first pullback to the newly broken resistance.",
          },
          {
            type: 'fact',
            emoji: '🔗',
            heading: 'Connecting the Technical Level to Your Strike',
            body: "Your strike choice should reflect your technical view. If a stock bounces from $50 support and you think it goes to $55 resistance, an ATM ($50 strike) call makes sense. If you think it breaks $55 resistance and runs, a $55 OTM call gives you more leverage on that specific move.",
          },
          {
            type: 'chart-demo',
            demoType: 'price-range',
            emoji: '📊',
            heading: 'Find the Key Levels',
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Technical Options Entry',
            quiz: {
              question: "A stock breaks above $80 resistance on high volume. $80 was tested and held 4 times previously. What's the options setup?",
              options: [
                'Buy a put — resistance breaks often fail',
                'Buy a call — the breakout above confirmed resistance is a bullish signal',
                'Wait for the stock to return to $70 before entering',
                'Sell the stock short',
              ],
              correctIndex: 1,
              explanation: "A breakout above resistance that was tested 4 times and held is significant — the selling pressure at that level has been absorbed. A call entry on this breakout (or pullback to $80 as new support) is technically justified with a clear stop below $80.",
            },
          },
          {
            type: 'complete',
            emoji: '🧲',
            heading: 'Technical + Options Combined',
            body: "Support levels give you entry. Resistance levels give you targets. Now your chart reading directly informs every options trade.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op4-l3',
        title: 'Earnings Plays — High Risk, High Reward',
        emoji: '📋',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '📋',
            heading: 'The Most Dangerous Options Trade for Beginners',
            body: "Earnings reports move stocks 5-20%+ in a single day. Options traders dream about these moves. But earnings plays are also where most beginners lose money badly — because of IV crush, because they don't understand the mechanics, and because they break their rules.",
          },
          {
            type: 'text',
            emoji: '💥',
            heading: 'The IV Crush Review',
            body: "Before earnings, everyone buys options — driving IV sky high. After the announcement, IV collapses immediately. A stock can beat earnings and jump 5%, but if IV drops 40%, your call option still loses money. This isn't bad luck — it's math.",
          },
          {
            type: 'text',
            emoji: '📅',
            heading: 'The Pre-Earnings Strategy That Works',
            body: "Buy your options 2-3 weeks before the earnings date when IV is still building. As earnings approach and IV rises, your option gains value from both the directional move AND rising IV. Close the position before the announcement — collect the IV expansion, avoid the IV crush.",
          },
          {
            type: 'fact',
            emoji: '⚡',
            heading: "The Straddle — Betting on Movement, Not Direction",
            body: "A straddle = buy a call AND a put at the same strike. You profit if the stock makes a big enough move in EITHER direction. The risk: if the stock barely moves, both options lose to theta and IV crush. Straddles work best when you expect a huge move but don't know which way — before major announcements.",
          },
          {
            type: 'tap-reveal',
            emoji: '🛡️',
            heading: 'Rules for Earnings Plays',
            body: 'Tap to see the discipline framework for earnings trades.',
            tapReveal: "Rule 1: Never hold options through an earnings announcement until you've traded options for at least 6 months. Rule 2: If you play earnings, size at 0.5% of account — half your normal size. Rule 3: Use the pre-earnings IV run-up strategy. Rule 4: If you do hold through, define your loss as the full premium — treat it like a lottery ticket, not a trade.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Earnings Check',
            quiz: {
              question: "A company reports earnings and beats estimates. The stock jumps 6%. But your call option lost 25% of its value. The most likely explanation is:",
              options: [
                'The market maker made an error',
                'A 6% jump is not enough to overcome a deeply OTM strike',
                'IV crush — the collapse in IV after the announcement overwhelmed the directional gain',
                'You held the wrong type of option',
              ],
              correctIndex: 2,
              explanation: "IV crush is real. Pre-earnings IV spike meant your option was priced for a potentially huge move. A 6% move was smaller than implied — IV collapsed and the option price fell despite being directionally correct. This is why experienced traders close options before earnings, not after.",
            },
          },
          {
            type: 'complete',
            emoji: '📋',
            heading: 'Earnings Understood',
            body: "Earnings plays are advanced territory. The mechanism is clear, the risk is defined, and the pre-earnings strategy is your safest path in.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op4-l4',
        title: 'The Wheel — Income From Options',
        emoji: '🔄',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '🔄',
            heading: 'Making Money Whether the Stock Goes Up, Down, or Sideways',
            body: "The Wheel is a beginner-friendly income strategy that generates consistent premium — without needing to predict which direction the stock goes. It's one of the most popular strategies for growing small accounts steadily.",
          },
          {
            type: 'text',
            emoji: '1️⃣',
            heading: 'Step 1 — Sell a Cash-Secured Put',
            body: "Pick a stock you actually want to own. Sell a put at a strike BELOW the current price. You collect the premium immediately. The obligation: if the stock falls to your strike, you buy 100 shares at that price. You need enough cash to buy those 100 shares — that's the 'cash-secured' part.",
          },
          {
            type: 'text',
            emoji: '2️⃣',
            heading: 'Step 2 — If Assigned, Sell a Covered Call',
            body: "If the stock falls to your strike and you buy the shares, you now own 100 shares. Sell a covered call above your purchase price. You collect more premium. If the stock rises to that strike, your shares get called away at a profit. You made money on the shares AND the premium.",
          },
          {
            type: 'fact',
            emoji: '💰',
            heading: 'Why the Wheel Works',
            body: "You're always collecting premium. If the stock stays above your put strike, the put expires worthless — you keep the premium and run it again. If you're assigned, you own a stock you wanted to own at a cheaper price AND you collect more premium selling covered calls. The income is consistent.",
          },
          {
            type: 'text',
            emoji: '⚠️',
            heading: "What Can Go Wrong",
            body: "The Wheel works best on stable, quality stocks. If you run it on a volatile or weak stock and it crashes 40%, you're stuck owning shares at a loss — and covered call premiums won't recover you fast enough. Only wheel stocks you'd genuinely be comfortable holding long-term.",
          },
          {
            type: 'tap-reveal',
            emoji: '🧮',
            heading: 'Account Size Requirements',
            body: 'Tap to understand the capital needed for the Wheel.',
            tapReveal: "To sell a cash-secured put on a $50 stock, you need $5,000 cash (100 shares × $50) held in reserve as collateral. This is why the Wheel is typically for accounts $5,000+. With less capital, focus on buying calls and puts first, and save the Wheel for when your account grows.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Wheel Check',
            quiz: {
              question: "You sell a cash-secured put on a stock at a $45 strike and collect $1.50 ($150 total). The stock stays above $45 until expiration. What happens?",
              options: [
                'You lose $150 because the put expired',
                "You keep the $150 premium — the put expired worthless in your favor",
                'You must now buy 100 shares at $45',
                'The $150 is returned to the buyer',
              ],
              correctIndex: 1,
              explanation: "When you SELL an option and it expires worthless, you keep the entire premium. The put buyer lost their premium — you collected it. This is the core income mechanism of the Wheel: collecting premium on options that expire worthless.",
            },
          },
          {
            type: 'complete',
            emoji: '🔄',
            heading: 'The Wheel Is Turning',
            body: "Sell puts. Get paid. Either keep the premium or own quality stock at a discount. Sell covered calls. Get paid again. Repeat.",
            xpReward: 20,
          },
        ],
      },
      {
        id: 'op4-l5',
        title: 'Options Final Quiz',
        emoji: '🏆',
        xpReward: 40,
        slides: [
          {
            type: 'intro',
            emoji: '🏆',
            heading: 'Options Final Quiz',
            body: "Contracts, Greeks, entries, exits, trend trading, support/resistance, earnings, and the Wheel. Everything you've built comes together here.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "You own 1 call option with delta 0.45 and theta -0.06. The stock is flat for 3 days. What happened to your position?",
              options: [
                'Nothing — delta and theta only apply on days the stock moves',
                'Gained $18 from theta being positive',
                'Lost $18 — theta -0.06 × 100 shares × 3 days',
                'Lost $1.35 total',
              ],
              correctIndex: 2,
              explanation: "Theta -0.06 × 100 shares = $6 lost per day. Over 3 days = $18 lost to time decay. Delta had no impact because the stock didn't move. This is the real cost of holding options — every day has a price, regardless of whether the stock moves.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "IV Rank is 15. You have a bullish directional thesis supported by chart analysis. What does low IV Rank mean for your call purchase?",
              options: [
                "Bad time to buy — IV is too low to make money",
                "Good time to buy — options are historically cheap, limiting overpay risk",
                "IV Rank has no relevance to directional trades",
                "You should buy puts instead when IV is low",
              ],
              correctIndex: 1,
              explanation: "Low IV Rank (15) means options are near their cheapest level of the past year. Buying when IV is low means you're paying fair or below-fair value for the premium. If IV rises (which is likely from a low base), vega will actually help your position — on top of any directional gains.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "Your $4,000 account uses the 1% rule for options. You buy a call for $40 (max risk). It goes up 50% to $60. What should you do?",
              options: [
                'Hold for 100%+ — this one is working',
                'Take the $20 profit — 50% gain is within your target range',
                'Add more contracts since the trade is working',
                'Wait until expiration to close',
              ],
              correctIndex: 1,
              explanation: "A 50% gain on an options trade is an excellent, professional-level result. Closing here locks in $20 profit on a $40 risk — a 50% return. The temptation to hold for more is where most traders give back gains. Consistent 25-50% wins build accounts. Hero trades occasionally pay but usually don't.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "Which options strategy generates income by selling puts on stocks you want to own, then selling covered calls if assigned?",
              options: [
                'The Straddle',
                'The Iron Condor',
                'The Wheel',
                'The Long Call Spread',
              ],
              correctIndex: 2,
              explanation: "The Wheel: sell cash-secured puts to collect premium. If assigned, own shares at a discount. Sell covered calls on those shares for more premium. Repeat. It's called the Wheel because it keeps cycling — generating income at each step regardless of whether the stock rises, falls, or stays flat.",
            },
          },
          {
            type: 'complete',
            emoji: '🎯',
            heading: 'Options Track Complete.',
            body: "Contracts, Greeks, directional plays, trend trading, earnings, the Wheel. You have a complete options education. The rest is screen time — study your charts, paper trade your setups, and build your confidence trade by trade.",
            xpReward: 40,
          },
        ],
      },
    ],
  },
]
