import type { Lesson, Unit } from '@/lib/starter-lessons'

export const WEALTH_UNITS: Unit[] = [
  {
    id: 'wb1',
    title: 'Your Money Foundation',
    subtitle: 'The mindset and mechanics every wealth builder needs first.',
    color: 'bg-brand-purple/20',
    borderColor: 'border-brand-purple',
    lessons: [
      {
        id: 'wb1-l1',
        title: 'Assets vs Liabilities',
        emoji: '⚖️',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '⚖️',
            heading: 'The Most Important Distinction in Finance',
            body: "Rich Dad Poor Dad made this famous, but it's been true forever. Understanding the difference between an asset and a liability is the single most important mental shift in building wealth.",
          },
          {
            type: 'text',
            emoji: '📈',
            heading: 'What Is an Asset?',
            body: "An asset puts money INTO your pocket. Stocks that pay dividends, rental property that generates rent, a business that earns revenue. The wealthy spend their lives accumulating assets.",
          },
          {
            type: 'text',
            emoji: '📉',
            heading: 'What Is a Liability?',
            body: "A liability takes money OUT of your pocket. A car loan, credit card debt, a mortgage on your home. The monthly payment leaves your account and goes to someone else's asset.",
          },
          {
            type: 'fact',
            emoji: '🏠',
            heading: "Your Home Isn't Always an Asset",
            body: "This surprises people. If you're paying a mortgage and the house isn't generating income, it's a liability — money flows out every month. It becomes an asset when it generates more than it costs, or when it's paid off.",
          },
          {
            type: 'tap-reveal',
            emoji: '💡',
            heading: 'The Wealth-Building Formula',
            body: 'Tap to see how the wealthy think about every financial decision.',
            tapReveal: "Before every major purchase, wealthy people ask: is this an asset or a liability? They buy liabilities only after their assets generate enough to pay for them. The goal is to keep acquiring assets until your asset income covers your lifestyle — that's financial freedom.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Asset or Liability?',
            quiz: {
              question: "You buy 10 shares of a company that pays a quarterly dividend. Is this an asset or a liability?",
              options: [
                'Liability — you spent money buying it',
                'Asset — it puts money into your pocket regularly',
                'Neither — stocks are too risky to classify',
                'It depends on whether the price goes up',
              ],
              correctIndex: 1,
              explanation: "A dividend-paying stock puts money into your pocket on a regular schedule. That makes it an asset by definition — regardless of whether the price rises or falls.",
            },
          },
          {
            type: 'complete',
            emoji: '⚖️',
            heading: 'Foundation Laid',
            body: "Assets in, liabilities out. Every financial decision for the rest of your life runs through this filter.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'wb1-l2',
        title: 'How the Wealthy Use the Market',
        emoji: '🔧',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🔧',
            heading: 'A Tool, Not a Gamble',
            body: "Most people treat the stock market like a casino — trying to pick winners, time the market, get rich quick. Wealthy people treat it like a tool — using it systematically to make money work for them.",
          },
          {
            type: 'text',
            emoji: '🏗️',
            heading: 'They Play the Long Game',
            body: "Warren Buffett has held some stocks for 30+ years. The wealthy aren't watching tickers every hour — they invest in quality and let time do the work. Compound growth requires patience, not attention.",
          },
          {
            type: 'text',
            emoji: '📊',
            heading: 'They Own the Market, Not Just Stocks',
            body: "The majority of wealthy investors hold broad index funds — investments that own hundreds of companies at once. They're not betting on one company. They're betting that the economy keeps growing — which it has, historically, every decade.",
          },
          {
            type: 'fact',
            emoji: '📰',
            heading: "They Ignore the News",
            body: "Market crashes, recessions, political news — wealthy long-term investors tune it out. They know that reacting to headlines is what causes most people to buy high and sell low. Their strategy doesn't change based on what's trending.",
          },
          {
            type: 'tap-reveal',
            emoji: '🧘',
            heading: 'The Behavior That Actually Builds Wealth',
            body: "Tap to see what separates people who build wealth from those who don't.",
            tapReveal: "Consistency. Investing a set amount every month — regardless of whether the market is up or down — outperforms almost every other strategy over 20+ years. It's boring. It's not a story you tell at dinner. And it works better than almost anything else available to regular people.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Market Mindset Check',
            quiz: {
              question: "A recession hits and your portfolio drops 25%. A wealthy long-term investor would most likely:",
              options: [
                'Sell everything to stop further losses',
                'Panic and wait for the market to recover before investing again',
                'Continue investing on schedule — or even increase contributions',
                'Move everything to cash until things feel safe',
              ],
              correctIndex: 2,
              explanation: "Recessions are sales on stocks. A wealthy long-term investor sees a 25% drop as an opportunity to buy more at lower prices — not a reason to exit. Every recession in history has been followed by a recovery and new highs.",
            },
          },
          {
            type: 'complete',
            emoji: '🔧',
            heading: "Tool Calibrated",
            body: "The market is a tool. You now know how the people who built wealth with it actually use it.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'wb1-l3',
        title: 'Starting Small — The $150 Reality',
        emoji: '💰',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '💰',
            heading: "Your $150 Is Real Money",
            body: "You don't need $10,000 to start. The tools available today make any amount a real starting point. But there are things you need to know about trading and investing with a small account — things most people learn the hard way.",
          },
          {
            type: 'text',
            emoji: '🍰',
            heading: 'Fractional Shares Changed Everything',
            body: "Until recently, one share of Amazon cost $3,000+. You needed real money just to get started. Now, fractional shares let you buy $5 worth of any stock. $150 can own a piece of Apple, Tesla, and the S&P 500 all at once.",
          },
          {
            type: 'fact',
            emoji: '🧮',
            heading: 'The 1% Rule Still Works at Any Size',
            body: "$150 account → 1% = $1.50 max risk. Stock at $50, stop at $48 = $2 risk per share. $1.50 ÷ $2 = 0.75 shares. You buy a fraction. The math works exactly the same — you just own less of the position.",
          },
          {
            type: 'text',
            emoji: '🪞',
            heading: 'The Honest Conversation',
            body: "With $150, you will not generate income from trading. A great 20% return is $30. That's not a criticism — it's just math. The real value of starting small is learning the process with real emotional stakes. Real money creates real feelings. That's the lesson.",
          },
          {
            type: 'tap-reveal',
            emoji: '🧱',
            heading: "What a $150 Account Is Actually For",
            body: 'Tap for the mindset shift that changes everything.',
            tapReveal: "Practice with real stakes. When you risk $1.50 and lose it, you feel something. That feeling — and learning to stay disciplined through it — is worth more than any course. The traders who protect $15,000 later are the ones who respected their $1.50 limit now. The habit is the investment.",
          },
          {
            type: 'text',
            emoji: '🌊',
            heading: 'The Smarter Move for Small Amounts',
            body: "Putting $150 into an S&P 500 ETF like VOO or SPY, then adding $25–50 every month, will likely build more wealth than trying to trade individual stocks at this size. That's not settling — that's what most professional investors actually do with money they're not actively managing.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Small Account Strategy',
            quiz: {
              question: "You have $200 to invest. What's the most realistic expectation for year one?",
              options: [
                'Turn it into $2,000 through smart trades',
                'Build the habit, learn the process, and grow the account slowly',
                'Generate $300–500 in passive income',
                "It's too small to do anything meaningful with",
              ],
              correctIndex: 1,
              explanation: "The goal of a small account isn't income — it's education with real stakes. Every month you invest consistently, follow your rules, and don't blow up the account, you're building the discipline that matters at every account size.",
            },
          },
          {
            type: 'complete',
            emoji: '🌱',
            heading: 'Reality Check Complete',
            body: "Small doesn't mean pointless. It means you're building the foundation. Every wealthy investor started somewhere.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'wb1-l4',
        title: 'Money Foundation Quiz',
        emoji: '📝',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '📝',
            heading: 'Unit 1 Quiz',
            body: "Assets, wealth mindset, and starting small. Let's make sure the foundation is solid.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "Which of these is an asset?",
              options: [
                'A car you bought on a loan',
                'Credit card debt',
                'A rental property that earns more than it costs',
                'A mortgage payment on your primary home',
              ],
              correctIndex: 2,
              explanation: "An asset puts money into your pocket. A rental property that earns more than it costs generates positive cash flow — that's the definition of an asset.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "You have $300. Using the 1% rule, what's your max risk per trade? And if a stock has $3 risk per share, how many shares do you buy?",
              options: [
                '$3 max risk, 1 share',
                '$30 max risk, 10 shares',
                '$3 max risk, 10 shares',
                '$30 max risk, 1 share',
              ],
              correctIndex: 0,
              explanation: "1% of $300 = $3 max risk. $3 ÷ $3 risk per share = 1 share. With a small account, position sizing often means buying just 1 share — or a fraction. The math doesn't care about the size, only about keeping the loss within your limit.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "What is the primary benefit of starting to invest with a small amount, even if the profits are minimal?",
              options: [
                'Small accounts grow faster than large ones',
                'You avoid paying taxes at small amounts',
                'You build real habits and emotional discipline with actual stakes',
                'Brokers offer better rates for beginners',
              ],
              correctIndex: 2,
              explanation: "The discipline you build managing a small account — respecting your rules, staying calm during losses, investing consistently — is the same discipline that protects and grows large accounts. The habit is the real return.",
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Unit 1 Complete!',
            body: "Assets, the wealth mindset, and the honest truth about starting small. The foundation is built.",
            xpReward: 20,
          },
        ],
      },
    ],
  },
  {
    id: 'wb2',
    title: 'Building It',
    subtitle: 'Compound interest, purposeful saving, and choosing your vehicle.',
    color: 'bg-brand-green/10',
    borderColor: 'border-brand-green',
    lessons: [
      {
        id: 'wb2-l1',
        title: 'Saving With Purpose',
        emoji: '🪣',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🪣',
            heading: 'Three Buckets, One System',
            body: "Saving without a system is just hoping. A simple three-bucket system tells every dollar where to go before you spend it — which means you're never raiding your investment fund to cover an emergency.",
          },
          {
            type: 'text',
            emoji: '🛡️',
            heading: 'Bucket 1: Emergency Fund',
            body: "3–6 months of living expenses. Kept in a high-yield savings account — not invested. This is not wealth-building money. This is the money that keeps you from selling your investments at the worst possible time when life happens.",
          },
          {
            type: 'text',
            emoji: '📈',
            heading: 'Bucket 2: Investment Fund',
            body: "Money you invest every month, consistently, no matter what. This is the wealth-building bucket. It goes into index funds, individual stocks, or whatever your strategy is. It never gets touched for spending.",
          },
          {
            type: 'text',
            emoji: '🛍️',
            heading: 'Bucket 3: Spending Money',
            body: "What's left after emergency fund contributions and investing. This is guilt-free spending — you've already taken care of your future self. Enjoy it without regret.",
          },
          {
            type: 'fact',
            emoji: '⚡',
            heading: 'Pay Yourself First',
            body: "Move money to your investment bucket the same day you get paid — before you see it, before you spend it. This is the single habit change that most separates people who build wealth from people who mean to.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Bucket Check',
            quiz: {
              question: "Your car breaks down unexpectedly and costs $800 to fix. Which bucket should cover this?",
              options: [
                'Investment fund — sell some stocks',
                'Emergency fund — this is exactly what it is for',
                'Credit card — pay it back over time',
                'Skip investing this month to cover it',
              ],
              correctIndex: 1,
              explanation: "Your emergency fund exists for exactly this moment. Using it keeps you from selling investments at bad times or going into debt. After you use it, rebuild it before increasing investment contributions.",
            },
          },
          {
            type: 'complete',
            emoji: '🪣',
            heading: 'System Built',
            body: "Three buckets. Every dollar has a job. This system works at $500/month or $50,000/month.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'wb2-l2',
        title: 'Compound Interest — Why Time Beats Money',
        emoji: '⏰',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '⏰',
            heading: 'The Most Powerful Force in Wealth Building',
            body: "Albert Einstein allegedly called compound interest the eighth wonder of the world. Whether or not he said that, the math is real. Starting early matters more than starting big.",
          },
          {
            type: 'text',
            emoji: '🌱',
            heading: 'What Compound Interest Actually Is',
            body: "Simple interest earns on your original amount. Compound interest earns on your original amount AND on every dollar of interest you've already earned. Your gains generate their own gains. Over time, this becomes explosive.",
          },
          {
            type: 'fact',
            emoji: '🏆',
            heading: 'The Numbers That Should Motivate You',
            body: "$100/month starting at 22, at 10% annual return = $637,000 by 62. The same $100/month starting at 32 = $226,000 by 62. Same amount invested, same return, 10 years earlier — results in 2.8× more money. Time is the variable that matters most.",
          },
          {
            type: 'chart-demo',
            demoType: 'savings-vs-investing',
            emoji: '📈',
            heading: 'See Compound Growth in Action',
          },
          {
            type: 'tap-reveal',
            emoji: '💡',
            heading: "The Lesson Most People Learn Too Late",
            body: "Tap for the one insight that changes how urgently you start.",
            tapReveal: "Every year you wait to start investing costs you more than just one year of growth. It costs you all the compound growth that would have built on top of that year, for every year after. The 22-year-old investing $100/month doesn't just have 10 more years than the 32-year-old — they have 10 more years of compounding on everything. Start now, even if the amount feels embarrassingly small.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Compound Check',
            quiz: {
              question: "Investor A starts at 20 with $50/month. Investor B starts at 35 with $200/month. Both retire at 65, both earn 8% annually. Who likely has more?",
              options: [
                'Investor B — they invested 4× as much per month',
                'Investor A — they had 15 more years of compounding',
                'They end up about the same',
                "It depends on which stocks they picked",
              ],
              correctIndex: 1,
              explanation: "Investor A wins, despite investing far less per month. 45 years of compounding at 8% on $50/month grows to ~$174,000. Investor B at $200/month for 30 years grows to ~$244,000 — but Investor A invested $27,000 total versus Investor B's $72,000. Time is more powerful than the amount.",
            },
          },
          {
            type: 'complete',
            emoji: '⏰',
            heading: "Time Is Your Biggest Asset",
            body: "You now understand why every financial advisor says 'start now.' It's not a cliché — it's math.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'wb2-l3',
        title: 'ETFs vs Individual Stocks',
        emoji: '🗂️',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🗂️',
            heading: 'Which Vehicle Is Right for You?',
            body: "You've learned how to trade individual stocks. You've heard about ETFs. Now it's time to be honest about which one actually fits your life, your time, and your goals.",
          },
          {
            type: 'text',
            emoji: '🗂️',
            heading: 'What Is an ETF?',
            body: "An ETF (Exchange-Traded Fund) is a single investment that holds hundreds or thousands of stocks at once. VOO holds all 500 companies in the S&P 500. One purchase, instant diversification across the entire US economy.",
          },
          {
            type: 'fact',
            emoji: '📊',
            heading: 'The S&P 500 Track Record',
            body: "The S&P 500 has averaged ~10% annual returns over the last 100 years. Every 10-year period in history has been positive. It has survived two World Wars, the Great Depression, 2008, and COVID. Betting on the index means betting that the US economy keeps existing — a reasonable bet.",
          },
          {
            type: 'text',
            emoji: '🎯',
            heading: 'Individual Stocks — When They Make Sense',
            body: "Trading individual stocks makes sense if: you genuinely enjoy analyzing companies, you have time to monitor positions, and you've built the discipline from the Leveler track. It can outperform the index — but most people, most years, don't beat the S&P 500.",
          },
          {
            type: 'tap-reveal',
            emoji: '🤝',
            heading: "You Don't Have to Choose One",
            body: "Tap to see how most serious investors actually do it.",
            tapReveal: "Most investors do both. Core portfolio = ETFs (consistent, low-maintenance, compounding). Active allocation = individual stocks (the fun part, 10–20% of portfolio). The ETF core protects you. The individual stock allocation lets you learn and potentially outperform. Neither has to be 100%.",
          },
          {
            type: 'chart-demo',
            demoType: 'portfolio-bars',
            emoji: '📊',
            heading: 'Diversification in Practice',
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'ETF vs Stocks',
            quiz: {
              question: "Which statement best describes the main advantage of an S&P 500 ETF for a new investor?",
              options: [
                'It always outperforms individual stocks',
                'It requires no money to start',
                'It provides instant diversification across hundreds of companies with one purchase',
                'It protects you from all market downturns',
              ],
              correctIndex: 2,
              explanation: "One ETF purchase spreads your money across 500 companies instantly. That diversification is what most people spend years and thousands trying to build on their own — available in a single trade for any amount.",
            },
          },
          {
            type: 'complete',
            emoji: '🗂️',
            heading: 'Vehicle Chosen',
            body: "ETFs for the foundation, individual stocks for the growth. You now know how to use both.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'wb2-l4',
        title: 'Building It — Unit Quiz',
        emoji: '📝',
        xpReward: 20,
        slides: [
          {
            type: 'intro',
            emoji: '📝',
            heading: 'Unit 2 Quiz',
            body: "Purposeful saving, compound interest, and your investment vehicle. Let's lock it in.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "What is the primary purpose of an emergency fund in a wealth-building system?",
              options: [
                'To earn interest while you wait for investment opportunities',
                'To prevent you from selling investments at bad times when life happens',
                'To pay for planned large purchases like vacations',
                'To hold your investment gains safely',
              ],
              correctIndex: 1,
              explanation: "An emergency fund is your financial firewall. Without it, a car repair or medical bill forces you to sell investments — often at the worst possible time. With it, your investment bucket stays untouched.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "Two people invest $200/month at 8% annual returns. Person A starts at 25, Person B starts at 35. Who has more at 65?",
              options: [
                'Person B — they invested more aggressively',
                'About the same — same monthly amount',
                'Person A — 10 more years of compounding makes a massive difference',
                "It depends on which stocks they chose",
              ],
              correctIndex: 2,
              explanation: "Person A at 25 has 40 years of compounding — roughly $702,000. Person B at 35 has 30 years — roughly $298,000. Same monthly investment, same return rate. 10 years earlier more than doubles the outcome.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "What does a broad market ETF like VOO actually own?",
              options: [
                'A single large company',
                'Government bonds only',
                'All 500 companies in the S&P 500 index',
                'Real estate properties',
              ],
              correctIndex: 2,
              explanation: "VOO tracks the S&P 500 — it holds proportional shares in all 500 companies in the index. One purchase gives you exposure to Apple, Microsoft, Amazon, and 497 others simultaneously.",
            },
          },
          {
            type: 'complete',
            emoji: '🎓',
            heading: 'Unit 2 Complete!',
            body: "Saving with purpose, compound growth, ETFs vs stocks — you're building real financial intelligence now.",
            xpReward: 20,
          },
        ],
      },
    ],
  },
  {
    id: 'wb3',
    title: 'The Long Game',
    subtitle: 'Generational wealth, daily habits, and your next step.',
    color: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500',
    lessons: [
      {
        id: 'wb3-l1',
        title: 'Generational Wealth',
        emoji: '🌳',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🌳',
            heading: 'What Generational Wealth Actually Means',
            body: "Generational wealth isn't about being a billionaire. It's about breaking a cycle — building financial assets that outlast you and give the next generation a head start you never had.",
          },
          {
            type: 'text',
            emoji: '📖',
            heading: 'Why the Gap Exists',
            body: "Generational wealth compounds just like investment returns. A family that owned a home in 1970 passed down equity. A family that invested in the market in 1980 passed down a portfolio. Families without those assets start each generation from zero — not from behind, but from zero.",
          },
          {
            type: 'text',
            emoji: '🏗️',
            heading: 'What It Looks Like for Regular People',
            body: "It doesn't require a fortune. A $10,000 Roth IRA started for a child, a paid-off home, a life insurance policy, a brokerage account with clear beneficiaries. These aren't luxuries — they're building blocks that every family can work toward.",
          },
          {
            type: 'fact',
            emoji: '📚',
            heading: 'Financial Education Is Wealth Too',
            body: "Teaching your children how money works — assets, compound interest, the difference between spending and investing — is worth more than any dollar amount. Knowledge that breaks a pattern of financial confusion is generational wealth at its most powerful.",
          },
          {
            type: 'tap-reveal',
            emoji: '🌱',
            heading: "You're Already Doing It",
            body: "Tap to see what this lesson means for you right now.",
            tapReveal: "Every concept you've learned in Stockly is a piece of generational wealth. You're building financial literacy that most people never get — and that you can pass on. The cycle doesn't break when you become a millionaire. It breaks the moment you understand something your parents didn't and choose to act on it.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: 'Generational Wealth Check',
            quiz: {
              question: "Which of these is an example of generational wealth being passed down?",
              options: [
                'Buying your child expensive gifts every birthday',
                'Opening a Roth IRA for your child when they have their first job',
                'Letting your child borrow money interest-free',
                'Paying for a lavish college graduation party',
              ],
              correctIndex: 1,
              explanation: "A Roth IRA started early is one of the most powerful wealth-transfer tools available. Contributions grow tax-free for decades. Starting one for a child with their first job income gives them a 40+ year head start on retirement savings.",
            },
          },
          {
            type: 'complete',
            emoji: '🌳',
            heading: 'The Cycle Breaks Here',
            body: "You understand something today that changes what's possible for everyone who comes after you.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'wb3-l2',
        title: 'Your Next Step',
        emoji: '🚀',
        xpReward: 15,
        slides: [
          {
            type: 'intro',
            emoji: '🚀',
            heading: 'You Have the Knowledge — Now Build the Habit',
            body: "You've covered more ground than most people ever will. The hardest part isn't learning this — it's doing it consistently when life gets busy, the market gets scary, and motivation fades. Here's how to make it stick.",
          },
          {
            type: 'text',
            emoji: '📅',
            heading: 'Make It Automatic',
            body: "Set up automatic monthly contributions to your investment account the same day you get paid. Don't rely on remembering, feeling motivated, or checking the market first. Automation removes the decision — and the decision is usually where people fail.",
          },
          {
            type: 'text',
            emoji: '📔',
            heading: 'Review Once a Month, Not Every Day',
            body: "Check your portfolio once a month. Not daily. Daily watching breeds daily emotion — and emotional decisions destroy returns. Monthly reviews keep you informed without letting short-term noise drive long-term decisions.",
          },
          {
            type: 'fact',
            emoji: '📱',
            heading: "The Best Investment App Is One You Don't Open Every Day",
            body: "Studies show that investors who check their portfolios least frequently tend to outperform those who check daily. The urge to do something during volatility is the enemy. Your future self benefits most when your present self stays out of the way.",
          },
          {
            type: 'tap-reveal',
            emoji: '🏁',
            heading: 'Your Starting Checklist',
            body: 'Tap for the five things to do this week.',
            tapReveal: "(1) Open a brokerage account if you don't have one — Fidelity, Schwab, or Robinhood work for beginners. (2) Set up automatic monthly contributions — even $25 matters. (3) Buy your first ETF — VOO or SPY for simplicity. (4) Start an emergency fund if you don't have one — even $500 is a start. (5) Come back to Stockly. The learning never stops.",
          },
          {
            type: 'complete',
            emoji: '🎉',
            heading: "This Is Just the Beginning",
            body: "You've finished Stockly's core curriculum. The real journey — investing consistently, building habits, watching your wealth compound — starts now. You have everything you need.",
            xpReward: 15,
          },
        ],
      },
      {
        id: 'wb3-l3',
        title: 'Wealth Building Final Quiz',
        emoji: '🏆',
        xpReward: 30,
        slides: [
          {
            type: 'intro',
            emoji: '🏆',
            heading: 'The Final Quiz',
            body: "Assets, compound interest, small accounts, ETFs, generational wealth, and the habits that make it real. Everything comes together here.",
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "Which is the correct definition of an asset?",
              options: [
                'Anything you own that has value',
                'Something that puts money into your pocket',
                'Any investment that increases in price',
                'Money saved in a bank account',
              ],
              correctIndex: 1,
              explanation: "An asset puts money INTO your pocket. A car you own but pay insurance and maintenance on is not an asset by this definition — it takes money out. A rental property that earns income is an asset. The distinction is cash flow direction.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "You have $500. Using the 1% rule, you can risk $5 per trade. A stock is at $80 with a stop at $75 ($5 risk/share). How many shares do you buy?",
              options: ['1 share', '2 shares', '5 shares', '10 shares'],
              correctIndex: 0,
              explanation: "$5 max risk ÷ $5 risk per share = 1 share. Small account, small position — but the math is exact and the rule is respected. That discipline is what protects the account.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "What is the most important factor in building wealth through compound interest?",
              options: [
                'Picking the highest-returning stocks',
                'Starting as early as possible',
                'Investing large lump sums',
                'Timing the market correctly',
              ],
              correctIndex: 1,
              explanation: "Time is the most powerful factor in compounding. Starting early — even with small amounts — consistently outperforms starting later with larger amounts. Every year earlier you begin multiplies your outcome.",
            },
          },
          {
            type: 'quiz',
            emoji: '❓',
            heading: '',
            quiz: {
              question: "What is the real value of teaching financial literacy to the next generation?",
              options: [
                'They can manage your accounts for you',
                'It reduces your tax liability',
                'It breaks a cycle and gives them a head start you may not have had',
                "It only matters if you have significant assets to pass down",
              ],
              correctIndex: 2,
              explanation: "Financial education is generational wealth in its purest form. Knowledge that changes behavior — investing early, avoiding bad debt, understanding assets — compounds across generations regardless of how much money you pass down.",
            },
          },
          {
            type: 'complete',
            emoji: '💎',
            heading: 'Stockly Complete. 🎉',
            body: "From what a stock is to generational wealth — you've built a foundation most people never get. The market is no longer a mystery. Now go build something.",
            xpReward: 30,
          },
        ],
      },
    ],
  },
]
